#!/usr/bin/env python3
# Code generated by MCHP Chatbot
"""Captures a scope-like trace of PTT/TX/TX_VCC/TX_BIAS pins across a PTT assert/release
cycle by single-stepping the MPLAB X `mdb` simulator and polling pin state at fixed
instruction intervals, then renders a logic-analyzer-style PNG.

Timing is approximate: instruction counts are converted to seconds assuming one
instruction cycle per Stepi step at _XTAL_FREQ/4 (see firmware/include/pin_map.h).
This is close enough to see the shape/order of the sequencer delays, not a cycle-exact
measurement.

Usage:
    python tools/simulate/trace_ptt_sequence.py
    python tools/simulate/trace_ptt_sequence.py --test
    python tools/simulate/trace_ptt_sequence.py --temperature-trip
Requires: MPLAB X IDE (mdb), and matplotlib (pip install matplotlib) for the PNG output.
"""
import re
import subprocess
import sys
import tempfile
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent.parent
HEX_PATH = REPO_ROOT / "out" / "My_Pic_Project" / "default.hex"
# Loaded instead of the .hex so mdb can resolve C variable names (debug symbols).
ELF_PATH = REPO_ROOT / "out" / "My_Pic_Project" / "default.elf"
DEVICE = "PIC16F18855"

# Firmware globals that explain why PTT/TX may be blocked (see main.c).
STATE_VARS = [
    "g_startup_inhibit", "g_comparator_reset_active", "g_fault_latched", "g_trip_reason",
    "g_ptt_active", "g_sequence_stage", "g_state", "g_trip_shutdown_active"
]
TRIP_REASON_BITS = [
    (0x01, "SWR1"),
    (0x02, "SWR2"),
    (0x04, "HWFAULT"),
    (0x08, "CURRENT"),
    (0x10, "TEMPERATURE"),
    (0x20, "OVERDRIVE"),
    (0x40, "DRAIN"),
]
XTAL_FREQ = 32_000_000
SECONDS_PER_INSTRUCTION = 4 / XTAL_FREQ  # approx; 1 instruction cycle = 4 osc clocks

STEP_SIZE = 2000
PHASES = [
    # PTT idle (inactive, active-low), coarsely stepped through the bulk of
    # the ~1s startup-inhibit wait (see g_startup_elapsed_ms in main.c).
    ("steady_coarse", "5v", 22, 180000),  # ~495ms
    # Finer-grained stepping across the 1000ms boundary (with margin for
    # init overhead: lcd_init/adc_init delays before the main loop's ms
    # clock starts) so the ~10ms SETTLE (comparator reset) pulse isn't
    # skipped between samples.
    ("steady_mid", "5v", 402, 20000),  # ~495ms -> ~1500ms, 2.5ms/sample
    ("asserted", "0v", 300, STEP_SIZE),  # PTT pressed; covers both ~20ms sequencer delays
    ("released", "5v", 100, STEP_SIZE),  # PTT released again
]
PINS = ["RC1", "RC0", "RC5", "RC6", "RC7"]
PIN_LABELS = {"RC1": "SETTLE", "RC0": "PTT", "RC5": "RELAYS", "RC6": "TX_VCC", "RC7": "TX_BIAS"}
ADC_PINS = ["RA0", "RA1", "RA2", "RA3", "RA5", "RB1", "RB2", "RB3"]
ADC_LABELS = {
    "RA0": "SWR1 FWD", "RA1": "SWR1 REF", "RA2": "SWR2 FWD", "RA3": "SWR2 REF",
    "RA5": "TEMPERATURE", "RB1": "CURRENT", "RB2": "OVERDRIVE", "RB3": "DRAIN"
}


def find_mdb() -> Path:
    candidates = sorted(Path("C:/Program Files/Microchip/MPLABX").glob("*/mplab_platform/bin/mdb.bat"))
    if not candidates:
        candidates = sorted(Path("/Applications/microchip/mplabx").glob("*/mplab_platform/bin/mdb.sh"))
    if not candidates:
        sys.exit("error: mdb not found. Install MPLAB X IDE.")
    return candidates[-1]


# Code generated by MCHP Chatbot
def build_script(temperature_trip=False) -> str:
    lines = [f"device {DEVICE}", "hwtool sim", f"program {ELF_PATH}"]
    # --- Setup: Set all analog and relevant inputs to safe values ---
    lines += [
        "write pin RA0 0v", "write pin RA1 0v", "write pin RA2 0v", "write pin RA3 0v",
        "write pin RA5 2.5v", "write pin RB1 0v", "write pin RB2 0v", "write pin RB3 0v", "write pin RB4 0v"
    ]

    def sample():
        for pin in PINS:
            lines.append(f"print pin {pin}")
        for pin in ADC_PINS:
            lines.append(f"print pin {pin}")
        for var in STATE_VARS:
            lines.append(f"print {var}")

    if not temperature_trip:
        # --- Briefly assert PTT during startup; it must have no effect while inhibited ---
        lines.append("write pin RC0 0v")
        for _ in range(5):  # 50 ms while startup inhibit is active
            lines.append("Stepi 80000")
            sample()
        lines.append("write pin RC0 5v")

    # --- Finish the settle (startup inhibit) period: 1100ms total ---
    for _ in range(105 if not temperature_trip else 110):
        lines.append("Stepi 80000")  # 10 ms per print
        sample()
    # --- Assert PTT (pull RC0 low), triggering SETTLE high for 10 ms ---
    lines.append("write pin RC0 0v")
    # Fine-grained steps to catch SETTLE high pulse (comparator reset)
    for _ in range(12):  # ~12 ms sampled every 1 ms
        lines.append("Stepi 8000")
        sample()
    # Continue simulation for sequencer actions (TX, TX_VCC, etc), 200 ms more
    for _ in range(10 if temperature_trip else 40):
        lines.append("Stepi 40000")
        sample()
    # Hold PTT low for 500 ms before releasing it.
    for _ in range(100):
        lines.append("Stepi 40000")
        sample()
    if temperature_trip:
        # Raise the temperature stimulus from 2.5V to 5V over one simulated second.
        for step in range(1, 21):
            voltage = 2.5 + step * 0.125
            lines.append(f"write pin RA5 {voltage:.3f}v")
            if step < 20:
                lines.append("Stepi 400000")  # 50ms per ramp step
                sample()
            else:
                for _ in range(10):  # capture the five-millisecond shutdown sequence
                    lines.append("Stepi 8000")
                    sample()
        for _ in range(10):  # show the latched trip state for another 500ms
            lines.append("Stepi 400000")
            sample()
        lines.append("quit")
        return "\n".join(lines)
    # --- Release PTT (RC0 back high): relays open, then VCC, then bias ---
    lines.append("write pin RC0 5v")
    for _ in range(40):  # 5 ms steps, 40x5 = 200 ms
        lines.append("Stepi 40000")
        sample()
    lines.append("quit")
    return "\n".join(lines)

def run_mdb(mdb_path: Path, script: str) -> str:
    with tempfile.NamedTemporaryFile("w", suffix=".mdb", delete=False) as f:
        f.write(script)
        script_path = f.name
    try:
        result = subprocess.run(
            [str(mdb_path), script_path], capture_output=True, text=True, check=False
        )
        return result.stdout + result.stderr
    finally:
        Path(script_path).unlink(missing_ok=True)


PRINT_RE = re.compile(r"^(R[A-Z]\d+)\s+\S+\s+(?:(HIGH|LOW)|([\d.]+)V)", re.MULTILINE)
STEPI_RE = re.compile(r"^Stepi\s+(\d+)")
VAR_NAME_RE = re.compile(r"^(g_\w+)=$")


def block_reason(state: dict) -> str | None:
    """Returns a human-readable reason PTT/TX is blocked, or None if it isn't."""
    if state.get("g_startup_inhibit") == "true":
        return "STARTUP INHIBIT"
    if state.get("g_comparator_reset_active") == "true":
        return "SETTLE PULSE"
    if state.get("g_fault_latched") == "true":
        try:
            reason_bits = int(state.get("g_trip_reason", "0"))
        except ValueError:
            reason_bits = 0
        names = [name for bit, name in TRIP_REASON_BITS if reason_bits & bit]
        return "FAULT: " + "+".join(names) if names else "FAULT: UNKNOWN"
    return None


def validate_sequence(samples) -> None:
    """Fail when startup inhibit or either PTT sequencing direction is wrong."""
    startup_samples = [sample for sample in samples if sample[2]["g_startup_inhibit"] == "true"]
    if not any(sample[1]["RC0"] == 0 and all(sample[1][pin] == 1 for pin in ("RC5", "RC6", "RC7"))
               for sample in startup_samples):
        raise AssertionError("PTT was not ignored during startup inhibit")

    active_samples = [sample for sample in samples
                      if sample[2]["g_ptt_active"] == "true" and sample[2]["g_sequence_stage"] == "3"]
    if not active_samples:
        raise AssertionError("PTT active sequence did not reach stage 3")
    active = active_samples[0][1]
    if (active["RC5"], active["RC6"], active["RC7"]) != (0, 0, 0):
        raise AssertionError("active sequence did not drive RELAYS, TX_VCC, TX_BIAS low")

    release_samples = [sample for sample in samples if sample[2]["g_ptt_active"] == "false"]
    release_stage4 = next((sample for sample in release_samples if sample[2]["g_sequence_stage"] == "4"), None)
    release_stage5 = next((sample for sample in release_samples if sample[2]["g_sequence_stage"] == "5"), None)
    release_done = next((sample for sample in release_samples if sample[2]["g_sequence_stage"] == "0"
                         and sample[1]["RC5"] == 1 and sample[1]["RC6"] == 1 and sample[1]["RC7"] == 1), None)
    if release_stage4 is None or release_stage4[1]["RC5"] != 1 or release_stage4[1]["RC6"] != 0 or release_stage4[1]["RC7"] != 0:
        raise AssertionError("release did not raise RELAYS first")
    if release_stage5 is None or release_stage5[1]["RC5"] != 1 or release_stage5[1]["RC6"] != 1 or release_stage5[1]["RC7"] != 0:
        raise AssertionError("release did not raise TX_VCC second")
    if release_done is None:
        raise AssertionError("release did not raise TX_BIAS last")


def validate_temperature_trip(samples) -> None:
    trip = next((sample for sample in samples if block_reason(sample[2]) == "FAULT: TEMPERATURE"), None)
    if trip is None:
        raise AssertionError("temperature trip was not reported")
    if trip[2]["g_ptt_active"] != "true":
        raise AssertionError("temperature trip did not occur while PTT was active")
    shutdown = next((sample for sample in samples if sample[2]["g_trip_shutdown_active"] == "true"), None)
    if shutdown is None or (shutdown[1]["RC5"], shutdown[1]["RC6"], shutdown[1]["RC7"]) != (0, 1, 0):
        raise AssertionError("fault did not raise TX_VCC immediately before the delayed shutdown")
    shutdown_done = next((sample for sample in samples
                          if sample[2]["g_trip_shutdown_active"] == "false" and
                          block_reason(sample[2]) == "FAULT: TEMPERATURE"), None)
    if shutdown_done is None or (shutdown_done[1]["RC5"], shutdown_done[1]["RC6"], shutdown_done[1]["RC7"]) != (1, 1, 1):
        raise AssertionError("fault did not raise RELAYS and TX_BIAS after five milliseconds")
    if trip[3]["RA5"] < 4.0:
        raise AssertionError("temperature ADC input did not rise above 4V")
    print("ADC voltages at temperature trip: " +
          ", ".join(f"{pin}={trip[3][pin]:.3f}V" for pin in ADC_PINS))
    print("TEMP: 150 DEGC (FAULT: TEMPERATURE)")


def parse_trace(output: str):
    """Walks the mdb transcript in order, tracking cumulative instruction count and
    each pin's/variable's most-recently-printed value, sampling a full snapshot every
    time all pins and state variables have been reprinted (i.e. once per Stepi block)."""
    samples = []
    instr_count = 0
    pending = {}
    pending_adc = {}
    pending_voltages = {}
    state_pending = {}
    awaiting_var = None
    for raw_line in output.splitlines():
        line = raw_line.strip()
        m_stepi = STEPI_RE.match(line)
        if m_stepi:
            instr_count += int(m_stepi.group(1))
            continue
        if awaiting_var is not None:
            if line:
                state_pending[awaiting_var] = line
                awaiting_var = None
            continue
        m_var = VAR_NAME_RE.match(line)
        if m_var:
            awaiting_var = m_var.group(1)
            continue
        m = PRINT_RE.match(line)
        if m:
            pin, level, volts = m.groups()
            pending[pin] = 1 if level == "HIGH" or (volts is not None and float(volts) >= 2.5) else 0
            if pin in ADC_PINS:
                pending_adc[pin] = 1
                pending_voltages[pin] = float(volts) if volts is not None else (5.0 if level == "HIGH" else 0.0)
        if (len(pending) == len(PINS) + len(ADC_PINS) and
                len(pending_adc) == len(ADC_PINS) and len(state_pending) == len(STATE_VARS)):
            samples.append((instr_count, dict(pending), dict(state_pending), dict(pending_voltages)))
            pending.clear()
            pending_adc.clear()
            pending_voltages.clear()
            state_pending.clear()
    return samples


def main():
    test_mode = "--test" in sys.argv[1:]
    temperature_trip = "--temperature-trip" in sys.argv[1:]
    if not ELF_PATH.exists():
        sys.exit(f"error: {ELF_PATH} not found - build firmware first (build_firmware.ps1/.sh)")
    mdb_path = find_mdb()
    script = build_script(temperature_trip=temperature_trip)
    output = run_mdb(mdb_path, script)
    samples = parse_trace(output)
    if not samples:
        sys.exit("error: no samples parsed from mdb output - dumping raw output:\n" + output[-4000:])
    if test_mode:
        validate_sequence(samples)
        print("PTT sequencing test passed")
    if temperature_trip:
        validate_temperature_trip(samples)

    out_dir = REPO_ROOT / "_build" / "My_Pic_Project" / "sim"
    out_dir.mkdir(parents=True, exist_ok=True)
    trace_name = "temperature_trip_trace" if temperature_trip else "ptt_trace"
    csv_path = out_dir / f"{trace_name}.csv"
    with open(csv_path, "w") as f:
        f.write("time_s," + ",".join(PIN_LABELS[p] for p in PINS) +
            "," + ",".join(f"ADC_{pin}_V" for pin in ADC_PINS) +
            ",g_ptt_active,g_sequence_stage,g_state,block_reason\n")
        for instr_count, vals, state, adc_voltages in samples:
            t = instr_count * SECONDS_PER_INSTRUCTION
            reason = block_reason(state) or ""
            f.write(f"{t:.6f}," + ",".join(str(vals[p]) for p in PINS) +
                "," + ",".join(f"{adc_voltages[pin]:.3f}" for pin in ADC_PINS) +
                f",{state['g_ptt_active']},{state['g_sequence_stage']},{state['g_state']},{reason}\n")
    print(f"Wrote {csv_path} ({len(samples)} samples)")

    # Print console FAULT/blocking-reason transitions so "why can't PTT key up" is obvious
    # without having to read the plot.
    last_reason = object()
    for instr_count, _vals, state, _adc_voltages in samples:
        reason = block_reason(state)
        if reason != last_reason:
            t = instr_count * SECONDS_PER_INSTRUCTION * 1000
            print(f"t={t:8.2f}ms  {reason if reason else 'PTT OK (no block)'}")
            last_reason = reason

    try:
        import matplotlib.pyplot as plt
    except ImportError:
        print("matplotlib not installed; skipping PNG (pip install matplotlib)")
        return

    times = [s[0] * SECONDS_PER_INSTRUCTION * 1000 for s in samples]  # ms
    reasons = [block_reason(s[2]) for s in samples]

    # Contiguous [start, end, reason] spans where PTT/TX is blocked, for shading/labeling.
    block_spans = []
    span_start = None
    span_reason = None
    for t, reason in zip(times, reasons):
        if reason != span_reason:
            if span_reason is not None:
                block_spans.append((span_start, t, span_reason))
            span_start, span_reason = t, reason
    if span_reason is not None:
        block_spans.append((span_start, times[-1], span_reason))

    fig, axes = plt.subplots(len(PINS), 1, sharex=True, figsize=(10, 6))
    for ax, pin in zip(axes, PINS):
        values = [s[1][pin] for s in samples]
        ax.step(times, values, where="post")
        ax.set_ylim(-0.2, 1.2)
        ax.set_yticks([0, 1])
        ax.set_ylabel(f"{pin}\n{PIN_LABELS[pin]}", rotation=0, labelpad=34, va="center")
        ax.grid(True, alpha=0.3)
        for start, end, reason in block_spans:
            ax.axvspan(start, end, color="red", alpha=0.12)
        if temperature_trip:
            trip_time = times[next(index for index, sample in enumerate(samples)
                                   if block_reason(sample[2]) == "FAULT: TEMPERATURE")]
            ax.axvline(trip_time, color="red", linestyle="--", alpha=0.6)
    for start, end, reason in block_spans:
        axes[0].text((start + end) / 2, 1.35, reason, ha="center", va="bottom",
                     fontsize=7, color="red", clip_on=False)
    if temperature_trip:
        axes[2].annotate("RELAYS HIGH: TX INHIBITED",
                         xy=(trip_time, 1), xytext=(8, 12),
                         textcoords="offset points", color="red", fontsize=8,
                         arrowprops={"arrowstyle": "->", "color": "red"})
    axes[0].set_xlim(0, times[-1])
    axes[-1].set_xlabel("time (ms, approx)")
    fig.suptitle("PTT sequencing with temperature trip (simulated)" if temperature_trip
                 else "PTT assert/release sequencing (simulated)")
    fig.tight_layout()
    png_path = out_dir / f"{trace_name}.png"
    fig.savefig(png_path, dpi=120)
    print(f"Wrote {png_path}")

    if temperature_trip:
        trip_index = next(index for index, sample in enumerate(samples)
                          if block_reason(sample[2]) == "FAULT: TEMPERATURE")
        adc_fig, adc_axes = plt.subplots(len(ADC_PINS), 1, sharex=True, figsize=(10, 11))
        for ax, pin in zip(adc_axes, ADC_PINS):
            values = [sample[3][pin] for sample in samples]
            ax.plot(times, values, drawstyle="steps-post")
            ax.set_ylabel(f"{pin}\n{ADC_LABELS[pin]}", rotation=0, labelpad=34, va="center")
            ax.grid(True, alpha=0.3)
            ax.annotate(f"{values[trip_index]:.3f} V",
                        (times[trip_index], values[trip_index]),
                        xytext=(6, 4), textcoords="offset points", fontsize=8)
        adc_axes[-1].set_xlabel("time (ms, approx)")
        adc_fig.suptitle("ADC input voltages at temperature trip")
        adc_fig.tight_layout()
        adc_png_path = out_dir / "temperature_trip_adc_trace.png"
        adc_fig.savefig(adc_png_path, dpi=120)
        print(f"Wrote {adc_png_path}")


if __name__ == "__main__":
    main()

