#!/usr/bin/env python3
# Code generated by MCHP Chatbot
"""Captures a scope-like trace of PTT/TX/TX_VCC/TX_BIAS pins across a PTT assert/release
cycle by single-stepping the MPLAB X `mdb` simulator and polling pin state at fixed
instruction intervals, then renders a logic-analyzer-style PNG.

Timing is approximate: instruction counts are converted to seconds assuming one
instruction cycle per Stepi step at _XTAL_FREQ/4 (see firmware/include/pin_map.h).
This is close enough to see the shape/order of the sequencer delays, not a cycle-exact
measurement.

Usage:
    python tools/simulate/trace_ptt_sequence.py
    python tools/simulate/trace_ptt_sequence.py --test
    python tools/simulate/trace_ptt_sequence.py --temperature-trip
    python tools/simulate/trace_ptt_sequence.py --trip SWR1
    python tools/simulate/trace_ptt_sequence.py --swr1-1p5
Requires: MPLAB X IDE (mdb), and matplotlib (pip install matplotlib) for the PNG output.
"""
import os
import re
import subprocess
import sys
import tempfile
import threading
import time
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import first_dit_invariants as invariants  # noqa: E402
import platform_process as procutil  # noqa: E402

REPO_ROOT = Path(__file__).resolve().parent.parent.parent

# Which part the simulator models. `PICAMP_DEVICE` selects it so the same harness can drive the
# PIC18F47Q10 during the upgrade; PIC16F18875 stays the default so nothing changes for the
# existing device. The simulated part must match the image loaded into it, so this is one setting
# rather than something each harness decides for itself. An empty value counts as unset - a shell
# that exports `PICAMP_DEVICE=` should not be a hard error.
DEVICE = os.environ.get("PICAMP_DEVICE") or "PIC16F18875"

# The image directory carries the device name. It has to, because both devices would otherwise
# write `out/My_Pic_Project/default.elf` and the harness would load whichever was built last -
# with no error, just a wrong verdict, and fault injection poking addresses from the other
# device's .sym. CMake writes `<device>` via PICAMP_MCPU; the MCPU spelling is derived here from
# the long device name to keep one source of truth.
_DEVICE_MCPU = {
    "PIC16F18875": "16F18875",
    "PIC18F47Q10": "18F47Q10",
}.get(DEVICE, DEVICE)
IMAGE_DIR = REPO_ROOT / "out" / f"My_Pic_Project_{_DEVICE_MCPU}"

HEX_PATH = IMAGE_DIR / "default.hex"
# Loaded instead of the .hex so mdb can resolve C variable names (debug symbols).
ELF_PATH = IMAGE_DIR / "default.elf"

# Firmware globals that explain why PTT/TX may be blocked (see main.c).
STATE_VARS = [
    "g_startup_inhibit", "g_comparator_reset_active", "g_fault_latched", "g_trip_reason",
    "g_ptt_active", "g_sequence_stage", "g_state", "g_trip_shutdown_active",
    "g_ptt_complete_display_active", "g_transient_menu_display",
    "g_fc_status.current_band", "g_fc_status.band_locked", "g_fc_status.frequency_khz",
    "g_snoop_active", "g_band_established"
]
# STATE_BYPASS_SNOOP in firmware/src/main.c (appended last so existing numbering is stable).
STATE_BYPASS_SNOOP = 6
TRIP_REASON_BITS = [
    (0x01, "SWR1"),
    (0x02, "SWR2"),
    (0x04, "HWFAULT"),
    (0x08, "CURRENT"),
    (0x10, "TEMPERATURE"),
    (0x20, "OVERDRIVE"),
    (0x40, "DRAIN"),
]
XTAL_FREQ = 32_000_000
SECONDS_PER_INSTRUCTION = 4 / XTAL_FREQ  # approx; 1 instruction cycle = 4 osc clocks

STEP_SIZE = 2000
PHASES = [
    # PTT idle (inactive, active-low), coarsely stepped through the bulk of
    # the ~1s startup-inhibit wait (see g_startup_elapsed_ms in main.c).
    ("steady_coarse", "5v", 22, 180000),  # ~495ms
    # Finer-grained stepping across the 1000ms boundary (with margin for
    # init overhead: lcd_init/adc_init delays before the main loop's ms
    # clock starts) so the ~10ms SETTLE (comparator reset) pulse isn't
    # skipped between samples.
    ("steady_mid", "5v", 402, 20000),  # ~495ms -> ~1500ms, 2.5ms/sample
    ("asserted", "0v", 300, STEP_SIZE),  # PTT pressed; covers both ~20ms sequencer delays
    ("released", "5v", 100, STEP_SIZE),  # PTT released again
]
# RD2-RD7 are the per-band LPF select outputs. Sampling them lets the tests assert the
# relay selection itself, not just the firmware's internal current_band variable.
BAND_PINS = ["RD2", "RD3", "RD4", "RD5", "RD6", "RD7"]
BAND_PIN_FOR = {1: "RD2", 2: "RD3", 3: "RD4", 4: "RD5", 5: "RD6", 6: "RD7"}
BAND_OUT_OF_SPEC = 7
PINS = ["RC1", "RC0", "RC5", "RC6", "RC7"] + BAND_PINS
PIN_LABELS = {
    "RC1": "SETTLE", "RC0": "PTT", "RC5": "RELAYS", "RC6": "TX_VCC", "RC7": "TX_BIAS",
    "RD2": "BAND 160m", "RD3": "BAND 80m", "RD4": "BAND 40m",
    "RD5": "BAND 20m", "RD6": "BAND 15m", "RD7": "BAND 10m",
}
ADC_PINS = ["RA0", "RA1", "RA2", "RA3", "RA5", "RB1", "RB2", "RB3"]
ADC_LABELS = {
    "RA0": "SWR1 FWD", "RA1": "SWR1 REF", "RA2": "SWR2 FWD", "RA3": "SWR2 REF",
    "RA5": "TEMPERATURE", "RB1": "CURRENT", "RB2": "OVERDRIVE", "RB3": "DRAIN"
}
TRIP_ADC_PINS = {
    "SWR1": ["RA0", "RA1"], "SWR2": ["RA2", "RA3"],
    "SWR1_1P5": ["RA0", "RA1"],
    "TEMPERATURE": ["RA5"], "CURRENT": ["RB1"],
    "OVERDRIVE": ["RB2"], "DRAIN": ["RB3"], "HWFAULT": []
}
TRIP_NAMES = {"SWR1", "SWR2", "HWFAULT", "CURRENT", "OVERDRIVE", "DRAIN", "TEMPERATURE"}
NON_TRIP_NAMES = {"SWR1_1P5"}
# Nominal in-band frequencies used by the Timer1 register-injection stimulus.
# Note there is no injectable true 10m representative: a real 10m frequency
# (28000-29700 kHz) needs 70000-74250 Timer1 counts, which exceeds the single 16-bit
# TMR1 write this harness performs, so 25000 kHz is the highest injectable value that
# still lands in the classifier's 10m window (>24500 and <=32000 kHz). The SCL
# stimulus test (--freq-scl) covers 160m/80m end-to-end; see docs in TESTING.md.
ALL_BAND_TESTS = [
    ("160m", 1800, 1),
    ("80m", 3600, 2),
    ("40m", 7000, 3),
    ("20m", 14000, 4),
    ("15m", 21000, 5),
    ("10m", 25000, 6),
]
BAND_TESTS = list(ALL_BAND_TESTS)


def injected_frequency_for(freq_khz):
    """Frequency to inject during another band's TX.

    It must differ from the band under test, otherwise a failure to freeze the band
    selection would be invisible. The previous next-index scheme injected the same
    frequency when BAND_TESTS held one entry (--quick-bands), making the lock
    assertion vacuous.
    """
    for _, candidate_khz, _ in ALL_BAND_TESTS:
        if candidate_khz != freq_khz:
            return candidate_khz
    raise AssertionError("need at least two distinct band frequencies to test locking")


def find_mdb() -> Path:
    """The MPLAB X `mdb` launcher for this machine (see platform_process.find_mdb).

    Kept as a thin alias because `test_first_dit.py` and `test_suite.py` call
    `harness.find_mdb()`, and the discovery itself belongs with the rest of the
    per-platform plumbing rather than duplicated here.
    """
    return procutil.find_mdb()


# Code generated by MCHP Chatbot
def build_script(trip_name=None) -> str:
    temperature_trip = trip_name == "TEMPERATURE"
    lines = [f"device {DEVICE}", "hwtool sim", f"program {ELF_PATH}"]
    # --- Setup: Set all analog and relevant inputs to safe values ---
    lines += [
        "write pin RA0 0v", "write pin RA1 0v", "write pin RA2 0v", "write pin RA3 0v",
        "write pin RA5 2.5v", "write pin RB1 0v", "write pin RB2 0v", "write pin RB3 0v", "write pin RB4 0v",
        "write pin RC2 5v", "write pin RB0 5v", "write pin RB6 5v"
    ]

    def sample():
        for pin in PINS:
            lines.append(f"print pin {pin}")
        for pin in ADC_PINS:
            lines.append(f"print pin {pin}")
        for var in STATE_VARS:
            lines.append(f"print {var}")

    def write_tmr1_count(freq_khz):
        """Inject the Timer1 count that the firmware's own scaling maps to freq_khz.

        Why this is register injection instead of a real clock on T1CKI: the MPLAB X
        simulator does not implement Timer1's external clock selection. It warns
        "W0106-SIM: This device only has partial support for TMR1 peripheral ... timer
        clock selection is not implemented". Driving RD1 with an SCL stimulus
        (mdb `stim`, verified 2026-09-21) leaves TMR1L/TMR1H at 0 even though the pin
        is actively driven (print pin RD1 reports HIGH/Din) and T1CON reads 0x27
        (TMR1ON, RD16, nSYNC, CKPS=1:4, CS=00=T1CKI).

        So a true end-to-end RF frequency-counter test is not possible in the simulator.
        Writing the count exercises the frequency maths, classification, band-select
        outputs and the TX lock logic, but it does NOT cover the T1CKI pin, the PPS
        routing, the 1:4 prescaler, or the Timer1 overflow path.

        counts = freq_khz * 1000 / 400  (inverse of the firmware's pulses*2/5)
        """
        total_counts = int(round((freq_khz * 1000.0) / 400.0))
        if total_counts > 0xFFFF:
            raise ValueError(f"{freq_khz} kHz cannot be represented by a 16-bit Timer1 write")
        lines.append(f"write TMR1L 0x{total_counts & 0xFF:02X}")
        lines.append(f"write TMR1H 0x{(total_counts >> 8) & 0xFF:02X}")

    def inject_step_hold(freq_khz, ms, chunk_ms=5):
        """Advance `ms` of simulated time with the snoop signal held present throughout.

        A single injection before a long step is not enough: the firmware resets TMR1 on every
        10 ms tick, so only the first tick of the step would see the injected count and the rest
        would read an empty gate window, which the classifier reports as its 160m no-signal
        default. Injecting before each `chunk_ms` chunk keeps the measured band stable for the
        whole step, exactly as continuous RF would.
        """
        for _ in range(ms // chunk_ms):
            write_tmr1_count(freq_khz)
            lines.append(f"Stepi {chunk_ms * 8000}")
        sample()

    def band_preflight(all_bands=False):
        band_tests = BAND_TESTS if all_bands else [("40m", 7000, 3)]
        for band_name, freq_khz, expected_band in band_tests:
            lines.append(f"# BAND PREFLIGHT: {band_name} @ {freq_khz} kHz (expected {expected_band})")
            # 5 ms steps, not 10 ms: the firmware resets TMR1 on every 10 ms tick, and a 10 ms
            # sample interval aliases with that tick. When it aliases badly *every* sample lands
            # before the tick that consumes the injected count, so the reading is never observed
            # and the assertion fails on a stimulus artefact rather than on firmware behaviour.
            # At 5 ms every tick window contains at least one post-tick sample.
            for _ in range(8):
                write_tmr1_count(freq_khz)
                lines.append("Stepi 40000")
                sample()
        lines.append("# Restore 40m before scenario PTT stimulus")
        for _ in range(8):
            write_tmr1_count(7000)
            lines.append("Stepi 40000")
            sample()

    if trip_name == "SWR1_1P5":
        lines[3:5] = ["write pin RA0 5.000v", "write pin RA1 0.200v"]
    if trip_name == "FREQ_CTR":
        # --- Finish startup inhibit period (1050ms) ---
        for _ in range(105):
            lines.append("Stepi 80000")
            sample()

        band_preflight(all_bands=True)
        for band_name, freq_khz, expected_band in BAND_TESTS:
            injected_freq_khz = injected_frequency_for(freq_khz)
            lines.append(f"# TX BAND CHECK: {band_name} @ {freq_khz} kHz, inject {injected_freq_khz} kHz")
            for _ in range(10):
                write_tmr1_count(freq_khz)
                lines.append("Stepi 40000")
                sample()
            lines.append("write pin RC0 0v")
            for _ in range(12):
                write_tmr1_count(freq_khz)
                lines.append("Stepi 8000")
                sample()
            for _ in range(20):
                write_tmr1_count(freq_khz)
                lines.append("Stepi 40000")
                sample()
            for _ in range(20):
                write_tmr1_count(injected_freq_khz)
                lines.append("Stepi 40000")
                sample()
            lines.append("write pin RC0 5v")
            for _ in range(30):
                write_tmr1_count(freq_khz)
                lines.append("Stepi 40000")
                sample()

        lines.append("quit")
        return "\n".join(lines)

    if trip_name == "FREQ_CTR_FAIL":
        for _ in range(105):
            lines.append("Stepi 80000")
            sample()
        lines.append("# No Timer1 writes: simulate a missing frequency-counter signal")
        lines.append("write pin RC0 0v")
        for _ in range(20):
            lines.append("Stepi 80000")
            sample()
        lines.append("write pin RC0 5v")
        for _ in range(5):
            lines.append("Stepi 80000")
            sample()
        lines.append("quit")
        return "\n".join(lines)

    if not temperature_trip:
        # --- Briefly assert PTT during startup; it must have no effect while inhibited ---
        lines.append("write pin RC0 0v")
        for _ in range(5):  # 50 ms while startup inhibit is active
            lines.append("Stepi 80000")
            sample()
        lines.append("write pin RC0 5v")

    # --- Finish the settle (startup inhibit) period: 1100ms total ---
    for _ in range(105 if not temperature_trip else 110):
        lines.append("Stepi 80000")  # 10 ms per print
        sample()
    band_preflight()
    # --- Assert PTT (pull RC0 low), triggering SETTLE high for 10 ms ---
    # The radio transmits once PTT is asserted, so keep the 40m snoop signal present for the
    # whole keyed window. Without this the injected measurement goes stale (the 10 ms tick
    # resets TMR1, so the next tick reads zero counts) and the firmware correctly refuses to
    # leave bypass: "RF present while receiving, silent while transmitting" is the opposite of
    # a real transmission. See docs/first-dit-band-detection.md.
    lines.append("write pin RC0 0v")
    # Fine-grained steps to catch SETTLE high pulse (comparator reset)
    for _ in range(12):  # ~12 ms sampled every 1 ms
        write_tmr1_count(7000)
        lines.append("Stepi 8000")
        sample()
    # Continue simulation for sequencer actions (TX, TX_VCC, etc), 200 ms more
    for _ in range(10 if temperature_trip else 40):
        write_tmr1_count(7000)
        lines.append("Stepi 40000")
        sample()
    # Hold PTT low for 500 ms before releasing it.
    for _ in range(100):
        write_tmr1_count(7000)
        lines.append("Stepi 40000")
        sample()

    if trip_name == "SWR1_1P5":
        lines.append("write pin RA0 5.000v")
        lines.append("write pin RA1 0.200v")
        for _ in range(20):  # prove 1.5:1 remains in TX for another 100ms
            lines.append("Stepi 40000")
            sample()
        lines.append("quit")
        return "\n".join(lines)
    if trip_name and not temperature_trip:
        if trip_name == "CURRENT":
            for step in range(1, 21):
                current_a = 20 + step * 1.5
                voltage = 2.5 + (current_a / 70.0) * 2.5
                lines.append(f"write pin RB1 {voltage:.3f}v")
                if current_a >= 41:
                    for _ in range(10):  # capture the five-millisecond trip shutdown
                        lines.append("Stepi 8000")
                        sample()
                    break
                lines.append("Stepi 400000")  # 50ms per ramp step
                sample()
            lines.append("write pin RB1 0.000v")  # sensor output falls when TX is removed
            for _ in range(10):
                lines.append("Stepi 40000")
                sample()
            safe_inputs = {"CURRENT": [("RB1", 2.857)]}  # 10A maximum on the next PTT attempt
        else:
            safe_inputs = None
        trip_inputs = {
            "SWR1": [("RA0", 2.500), ("RA1", 0.750)],
            "SWR2": [("RA2", 2.500), ("RA3", 0.400)],
            "HWFAULT": [("RB4", 5.000)],
            "CURRENT": [("RB1", 5.000)],
            "OVERDRIVE": [("RB2", 5.000)],
            "DRAIN": [("RB3", 5.000)],
        }
        if trip_name != "CURRENT":
            for pin, voltage in trip_inputs[trip_name]:
                lines.append(f"write pin {pin} {voltage:.3f}v")
            for _ in range(40):
                lines.append("Stepi 8000")
                sample()
            for _ in range(10):  # show the latched trip state for another 50ms
                lines.append("Stepi 40000")
                sample()
        if safe_inputs is None:
            safe_inputs = {
            "SWR1": [("RA0", 0.0), ("RA1", 0.0)],
            "SWR2": [("RA2", 0.0), ("RA3", 0.0)],
            "HWFAULT": [("RB4", 0.0)], "CURRENT": [("RB1", 0.0)],
            "OVERDRIVE": [("RB2", 0.0)], "DRAIN": [("RB3", 0.0)]
            }
        for pin, voltage in safe_inputs[trip_name]:
            lines.append(f"write pin {pin} {voltage:.3f}v")
        lines.append("write pin RC0 5v")
        for _ in range(10):
            write_tmr1_count(7000)
            lines.append("Stepi 40000")
            sample()
        lines.append("write pin RC0 0v")
        for _ in range(50):
            write_tmr1_count(7000)
            lines.append("Stepi 8000")
            sample()
        lines.append("quit")
        return "\n".join(lines)
    if temperature_trip:
        # The operator keeps the key down through the whole thermal cycle, so the radio is
        # transmitting throughout: keep the 40m snoop signal present so the amplifier can
        # re-establish the band after the trip clears (it must never key on the classifier's
        # no-signal default - see docs/first-dit-band-detection.md).
        # Raise the temperature stimulus from 2.5V to 5V over one simulated second.
        for step in range(1, 21):
            voltage = 2.5 + step * 0.125
            lines.append(f"write pin RA5 {voltage:.3f}v")
            if step < 20:
                inject_step_hold(7000, 50)  # 50ms per ramp step, signal held present
            else:
                for _ in range(10):  # capture the five-millisecond shutdown sequence
                    write_tmr1_count(7000)
                    lines.append("Stepi 8000")
                    sample()
        for _ in range(10):  # show the latched trip state for another 500ms
            inject_step_hold(7000, 50)
        # Lower the temperature stimulus back to 2.5V over two simulated seconds.
        for step in range(19, -1, -1):
            voltage = 2.5 + step * 0.125
            lines.append(f"write pin RA5 {voltage:.3f}v")
            inject_step_hold(7000, 50)  # recovery ramp; the radio is still transmitting
        lines.append("quit")
        return "\n".join(lines)
    # --- Release PTT (RC0 back high): relays open, then VCC, then bias ---
    lines.append("write pin RC0 5v")
    for _ in range(40):  # 5 ms steps, 40x5 = 200 ms
        lines.append("Stepi 40000")
        sample()
    lines.append("quit")
    return "\n".join(lines)

# Benign, expected MDB noise. The simulator has no clock-source mux for TMR1/TMR3/TMR5,
# and this firmware never configures those timers, so the warning fires on every reset and
# means nothing here (see Ai-Notes.txt). It is stripped from everything the harness shows or
# logs, because it otherwise buries the progress lines and turns up in the stderr tail of an
# unrelated failure. run_sim.sh/.ps1 have filtered the same token for exactly this reason.
#
# Stripping is display-only: these lines match no parser pattern, so removing them cannot
# change a pin/variable reading. A chunk boundary could in principle split the token, which
# would leave a harmless partial line - it can never corrupt a value the parser accepts.
MDB_NOISE_TOKENS = ("W0106-SIM",)


def strip_mdb_noise(text: str) -> str:
    """Drop lines containing a benign MDB noise token, leaving everything else verbatim."""
    if not any(token in text for token in MDB_NOISE_TOKENS):
        return text
    return "".join(
        line
        for line in text.splitlines(keepends=True)
        if not any(token in line for token in MDB_NOISE_TOKENS)
    )


def run_mdb(mdb_path: Path, script: str, timeout: float = 1500) -> str:
    """Run one mdb session to completion and return its combined output.

    `timeout` is a last-resort net, not the budget: `run_suite_with_watchdog.py` owns the
    real budget and kills the whole tree when it expires, so this has to sit *above* the
    launcher's `--timeout` for the launcher to win the race and report a clean
    `TIMEOUT ... END code=` line instead of the child dying first.

    The value is sized for the slowest supported host, because MDB's speed is a property
    of its JVM plus the simulator, not of this repo: measured 2026-09-22, the merged suite
    takes 356 s on Windows 10 against ~150 s on macOS and the first-dit proof ~55 s
    against ~20 s (2.4x), so the old 280 s default killed healthy Windows runs mid-flight.
    Do not shrink this back to a macOS-sized number.
    """
    with tempfile.NamedTemporaryFile("w", suffix=".mdb", delete=False) as f:
        f.write(script)
        script_path = f.name
    try:
        # stdin=DEVNULL + platform_process.isolated_spawn_kwargs() detach mdb from our
        # controlling tty so a killed/hung mdb/JVM can never leave the terminal in raw
        # mode (see bugfixes.md). That is start_new_session on POSIX; on Windows, where
        # the argument is ignored, it is CREATE_NEW_PROCESS_GROUP instead.
        proc = subprocess.Popen(
            [str(mdb_path), script_path], stdin=subprocess.DEVNULL,
            stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True,
            **procutil.isolated_spawn_kwargs(),
        )
        debug_path = os.environ.get("PICAMP_MDB_DEBUG_LOG")
        if debug_path:
            debug_file = open(debug_path, "a", buffering=1)
            debug_lock = threading.Lock()
            captured = {"stdout": [], "stderr": []}
            byte_counts = {"stdout": 0, "stderr": 0}
            # Partial lines carried between reads. A pipe read of 4096 bytes splits MDB output
            # wherever it happens to land, so writing each chunk straight through put half-lines
            # in the log - the reader watching it saw `ault_latched` rather than
            # `g_fault_latched` and reasonably called it strange output (user report, 2026-09-22).
            # Nothing is written until a full line is available; the tail of a read is held here.
            partial = {"stdout": "", "stderr": ""}

            def drain_stream(stream_name, stream):
                for chunk in iter(lambda: stream.read(4096), ""):
                    # Filtered here, at the single capture point, so the transcript the parser
                    # sees, the live debug log, the heartbeat byte counts and the stderr tail
                    # printed on failure are all free of the benign reset warning.
                    chunk = strip_mdb_noise(chunk)
                    if not chunk:
                        continue
                    captured[stream_name].append(chunk)
                    byte_counts[stream_name] += len(chunk.encode(errors="replace"))
                    # Raw text, deliberately NOT a repr: `{chunk!r}` turns every newline into a
                    # literal "\n" and every tab into "\t", and MDB's pin dumps are
                    # tab-separated tables, so escaping renders the log unreadable for the
                    # human watching the run (user feedback, 2026-09-22).
                    #
                    # One `os`-level write per complete line (for stderr, a line at a time) so
                    # a reader tailing this file always sees whole records.
                    buffered = partial[stream_name] + chunk
                    sep = "\n" if stream_name == "stdout" else "\r\n"
                    if sep in buffered:
                        head, _, partial[stream_name] = buffered.rpartition(sep)
                        with debug_lock:
                            debug_file.write(head + sep)
                    else:
                        partial[stream_name] = buffered[:8192]

            debug_file.write(
                f"[{time.strftime('%Y-%m-%dT%H:%M:%S%z')}] MDB_START pid={proc.pid}\n"
            )
            readers = [
                threading.Thread(target=drain_stream, args=("stdout", proc.stdout), daemon=True),
                threading.Thread(target=drain_stream, args=("stderr", proc.stderr), daemon=True),
            ]
            for reader in readers:
                reader.start()
            try:
                proc.wait(timeout=timeout)
            except subprocess.TimeoutExpired:
                procutil.kill_tree(proc.pid)
                proc.wait()
                for reader in readers:
                    reader.join(timeout=2)
                stderr_tail = "".join(captured["stderr"])[-2000:]
                if stderr_tail:
                    debug_file.write(
                        f"[{time.strftime('%Y-%m-%dT%H:%M:%S%z')}] MDB_STDERR_TEXT_BEGIN\n"
                        f"{stderr_tail}\n"
                        f"[{time.strftime('%Y-%m-%dT%H:%M:%S%z')}] MDB_STDERR_TEXT_END\n"
                    )
                debug_file.write(
                    f"[{time.strftime('%Y-%m-%dT%H:%M:%S%z')}] MDB_STDERR_TAIL "
                    f"bytes={byte_counts['stderr']} tail={stderr_tail!r}\n"
                )
                debug_file.write(
                    f"[{time.strftime('%Y-%m-%dT%H:%M:%S%z')}] MDB_TIMEOUT "
                    f"stdout_bytes={byte_counts['stdout']} stderr_bytes={byte_counts['stderr']}\n"
                )
                debug_file.close()
                sys.exit(f"error: mdb timed out after {timeout}s and was killed")
            for reader in readers:
                reader.join(timeout=2)
            stderr_tail = "".join(captured["stderr"])[-2000:]
            if stderr_tail:
                debug_file.write(
                    f"[{time.strftime('%Y-%m-%dT%H:%M:%S%z')}] MDB_STDERR_TEXT_BEGIN\n"
                    f"{stderr_tail}\n"
                    f"[{time.strftime('%Y-%m-%dT%H:%M:%S%z')}] MDB_STDERR_TEXT_END\n"
                )
                debug_file.write(
                    f"[{time.strftime('%Y-%m-%dT%H:%M:%S%z')}] MDB_STDERR_TAIL "
                    f"bytes={byte_counts['stderr']} tail={stderr_tail!r}\n"
                )
            debug_file.write(
                f"[{time.strftime('%Y-%m-%dT%H:%M:%S%z')}] MDB_EXIT "
                f"status={'PASS' if proc.returncode == 0 else 'FAIL'} "
                f"code={proc.returncode} stdout_bytes={byte_counts['stdout']} "
                f"stderr_bytes={byte_counts['stderr']} "
                f"stderr_tail={'logged' if stderr_tail else 'empty'}\n"
            )
            debug_file.close()
            if proc.returncode != 0:
                sys.exit(f"error: mdb exited with code {proc.returncode}; stderr tail: {stderr_tail[-500:]}")
            return "".join(captured["stdout"] + captured["stderr"])
        try:
            stdout, stderr = proc.communicate(timeout=timeout)
        except subprocess.TimeoutExpired:
            procutil.kill_tree(proc.pid)
            proc.communicate()
            sys.exit(f"error: mdb timed out after {timeout}s and was killed")
        return stdout + stderr
    finally:
        Path(script_path).unlink(missing_ok=True)


PRINT_RE = re.compile(r"^(R[A-Z]\d+)\s+\S+\s+(?:(HIGH|LOW)|([\d.]+)V)", re.MULTILINE)
STEPI_RE = re.compile(r"^Stepi\s+(\d+)")
VAR_NAME_RE = re.compile(r"^(g_[\w\.]+)=$")


def block_reason(state: dict) -> str | None:
    """Returns a human-readable reason PTT/TX is blocked, or None if it isn't."""
    if state.get("g_startup_inhibit") == "true":
        return "STARTUP INHIBIT"
    if state.get("g_comparator_reset_active") == "true":
        return "PTT_RESET_PULSE"
    if state.get("g_fault_latched") == "true":
        try:
            reason_bits = int(state.get("g_trip_reason", "0"))
        except ValueError:
            reason_bits = 0
        names = [name for bit, name in TRIP_REASON_BITS if reason_bits & bit]
        return "FAULT: " + "+".join(names) if names else "FAULT: UNKNOWN"
    return None


def validate_frequency_ready(samples, scenario_name="unknown") -> None:
    matches = [
        sample for sample in samples
        if sample[2].get("g_fc_status.frequency_khz") == "7000"
        and sample[2].get("g_fc_status.current_band") == "3"
    ]
    if not matches:
        print(f"FREQ_DEBUG scenario={scenario_name} missing valid 40m precondition", flush=True)
        raise AssertionError(f"{scenario_name}: frequency counter did not establish valid 40m PTT precondition")


def validate_band_coverage(samples, scenario_name="unknown") -> None:
    for band_name, freq_khz, expected_band in BAND_TESTS:
        matches = [
            sample for sample in samples
            if sample[2].get("g_fc_status.frequency_khz") == str(freq_khz)
            and sample[2].get("g_fc_status.current_band") == str(expected_band)
        ]
        if not matches:
            observed_pairs = sorted({
                (sample[2].get("g_fc_status.frequency_khz"),
                 sample[2].get("g_fc_status.current_band"))
                for sample in samples
            })
            observed_frequency = [
                (sample[2].get("g_fc_status.frequency_khz"),
                 sample[2].get("g_fc_status.current_band"),
                 sample[2].get("g_fc_status.band_locked"),
                 sample[2].get("g_ptt_active"),
                 sample[2].get("g_sequence_stage"))
                for sample in samples
                if sample[2].get("g_fc_status.frequency_khz") == str(freq_khz)
            ]
            print(f"FREQ_DEBUG scenario={scenario_name} samples={len(samples)}", flush=True)
            print(f"FREQ_DEBUG missing={band_name}@{freq_khz}kHz expected_band={expected_band}", flush=True)
            print(f"FREQ_DEBUG observed_pairs={observed_pairs}", flush=True)
            print(f"FREQ_DEBUG matching_frequency_states={observed_frequency}", flush=True)
            raise AssertionError(
                f"{scenario_name}: {band_name} band was not classified at {freq_khz} kHz"
            )


def validate_band_outputs(samples, scenario_name="FREQ_CTR") -> None:
    """Assert the RD2-RD7 band-select outputs agree with current_band.

    Checks the relay selection itself rather than only the internal current_band
    variable, so a regression in update_band_outputs() is caught.
    """
    checked = 0
    for sample in samples:
        # Before the scheduler runs, PORTD may not have been initialised yet.
        if sample[2].get("g_startup_inhibit") != "false":
            continue
        pins = sample[1]
        if not all(pin in pins for pin in BAND_PINS):
            raise AssertionError(f"{scenario_name}: band-select pins were not sampled")
        high = [pin for pin in BAND_PINS if pins[pin] == 1]
        band = sample[2].get("g_fc_status.current_band")
        if band == str(BAND_OUT_OF_SPEC):
            if high:
                raise AssertionError(
                    f"{scenario_name}: band-select outputs {high} driven while out of spec")
            checked += 1
            continue
        expected_pin = BAND_PIN_FOR.get(int(band)) if band and band.isdigit() else None
        if expected_pin is None:
            raise AssertionError(f"{scenario_name}: unexpected current_band value {band!r}")
        if high != [expected_pin]:
            raise AssertionError(
                f"{scenario_name}: band-select outputs {high} do not match "
                f"current_band={band} (expected exactly {expected_pin})")
        checked += 1
    if checked == 0:
        raise AssertionError(f"{scenario_name}: no samples checked for band-select outputs")


def validate_freq_ctr(samples, scenario_name="FREQ_CTR") -> None:
    validate_band_coverage(samples, scenario_name)
    validate_band_outputs(samples, scenario_name)
    for band_name, freq_khz, expected_band in BAND_TESTS:
        injected_freq_khz = injected_frequency_for(freq_khz)
        locked_injection = [
            sample for sample in samples
            if sample[2].get("g_ptt_active") == "true"
            and sample[2].get("g_sequence_stage") == "3"
            and sample[2].get("g_fc_status.band_locked") == "true"
            and sample[2].get("g_fc_status.current_band") == str(expected_band)
            and sample[2].get("g_fc_status.frequency_khz") == str(injected_freq_khz)
        ]
        if not locked_injection:
            raise AssertionError(
                f"{band_name} TX lock failed while injecting {injected_freq_khz} kHz"
            )
    print("FREQ_CTR passed: all bands classified, band-select outputs matched, "
          "and each band stayed locked during TX injection")


def validate_freq_ctr_failure(samples) -> None:
    """No decodable band must not key the amplifier (first-dit bypass snoop).

    Under the old semantics PTT itself was refused; now PTT is latched and the amplifier is
    held in bypass while the radio's first RF burst is snooped for. What must never happen
    is active TX, because the amplifier would then be amplifying through an unverified
    filter. See docs/first-dit-band-detection.md.
    """
    # Prove the stimulus actually drove PTT, otherwise a failed pin write would make
    # the rest of this negative test pass vacuously.
    if not any(sample[1].get("RC0") == 0 for sample in samples):
        raise AssertionError("PTT was never driven low, so bypass-snoop was not exercised")
    validate_band_outputs(samples, "FREQ_CTR_FAIL")
    latched = [sample for sample in samples if sample[2].get("g_ptt_active") == "true"]
    if not latched:
        raise AssertionError("PTT was not latched when the frequency counter had no signal")
    if any(sample[2].get("g_snoop_active") != "true" for sample in latched):
        raise AssertionError("latched PTT did not hold the amplifier in bypass-snoop")
    if any(sample[2].get("g_state") != str(STATE_BYPASS_SNOOP) for sample in latched):
        raise AssertionError("bypass-snoop did not report STATE_BYPASS_SNOOP")
    if any(sample[2].get("g_sequence_stage") != "0" for sample in samples):
        raise AssertionError("frequency-counter failure advanced the TX sequence")
    if any((sample[1]["RC5"], sample[1]["RC6"], sample[1]["RC7"]) != (1, 1, 1)
           for sample in samples):
        raise AssertionError("frequency-counter failure did not keep all TX outputs inactive")
    if any(sample[2].get("g_fc_status.band_locked") == "true" for sample in samples):
        raise AssertionError("the band was locked with no usable snoop measurement")
    print(f"FREQ_CTR_FAIL passed: no decodable band, so {len(latched)} samples held latched "
          "PTT in bypass-snoop with TX/TX_VCC/TX_BIAS inactive, stage 0 and the band unlocked")


def validate_sequence(samples) -> None:
    """Fail when startup inhibit or either PTT sequencing direction is wrong."""
    startup_samples = [sample for sample in samples if sample[2]["g_startup_inhibit"] == "true"]
    if not any(sample[1]["RC0"] == 0 and all(sample[1][pin] == 1 for pin in ("RC5", "RC6", "RC7"))
               for sample in startup_samples):
        raise AssertionError("PTT was not ignored during startup inhibit")

    active_samples = [sample for sample in samples
                      if sample[2]["g_ptt_active"] == "true" and sample[2]["g_sequence_stage"] == "3"]
    if not active_samples:
        raise AssertionError("PTT active sequence did not reach stage 3")
    active = active_samples[0][1]
    if (active["RC5"], active["RC6"], active["RC7"]) != (0, 0, 0):
        raise AssertionError("active sequence did not drive RELAYS, TX_VCC, TX_BIAS low")

    # Verify that frequency counter locked the band during stage 3 transmit
    band_locked_samples = [sample for sample in active_samples
                           if sample[2].get("g_fc_status.band_locked") == "true"]
    if not band_locked_samples:
        raise AssertionError("Frequency counter band was not locked during transmit stage 3")

    complete_display = next((sample for sample in samples
                             if sample[2]["g_ptt_complete_display_active"] == "true"), None)
    if complete_display is None or (complete_display[1]["RC5"], complete_display[1]["RC6"], complete_display[1]["RC7"]) != (0, 0, 0):
        raise AssertionError("PTT COMPLETE was displayed before all TX outputs went low")

    release_samples = [sample for sample in samples if sample[2]["g_ptt_active"] == "false"]
    release_stage4 = next((sample for sample in release_samples if sample[2]["g_sequence_stage"] == "4"), None)
    release_stage5 = next((sample for sample in release_samples if sample[2]["g_sequence_stage"] == "5"), None)
    release_done = next((sample for sample in release_samples if sample[2]["g_sequence_stage"] == "0"
                         and sample[1]["RC5"] == 1 and sample[1]["RC6"] == 1 and sample[1]["RC7"] == 1), None)
    if release_stage4 is None or release_stage4[1]["RC5"] != 1 or release_stage4[1]["RC6"] != 0 or release_stage4[1]["RC7"] != 0:
        raise AssertionError("release did not raise RELAYS first")
    if release_stage5 is None or release_stage5[1]["RC5"] != 1 or release_stage5[1]["RC6"] != 1 or release_stage5[1]["RC7"] != 0:
        raise AssertionError("release did not raise TX_VCC second")
    if release_done is None:
        raise AssertionError("release did not raise TX_BIAS last")

    # Verify that frequency counter unlocked after TX sequence completes (stage 0)
    if release_done[2].get("g_fc_status.band_locked") == "true":
        raise AssertionError("Frequency counter band remained locked after TX sequence completed")


def validate_trip(samples, trip_name) -> None:
    expected_reason = f"FAULT: {trip_name}"
    trip = next((sample for sample in samples if block_reason(sample[2]) == expected_reason), None)
    if trip is None:
        raise AssertionError(f"{trip_name} trip was not reported")
    if trip[2]["g_ptt_active"] != "true":
        raise AssertionError(f"{trip_name} trip did not occur while PTT was active")
    if trip_name == "CURRENT" and not 3.85 <= trip[3]["RB1"] <= 4.10:
        raise AssertionError(f"current trip occurred at {trip[3]['RB1']:.3f}V, outside the expected 40A threshold")
    fault_samples = [sample for sample in samples
                     if (block_reason(sample[2]) or "").startswith("FAULT:")]
    if any(sample[2]["g_ptt_complete_display_active"] == "true" for sample in fault_samples):
        raise AssertionError(f"{trip_name} fault display was overwritten by PTT_COMPLETE")
    tx_active = next((sample for sample in samples
                      if sample[2]["g_sequence_stage"] == "3" and
                      (sample[1]["RC5"], sample[1]["RC6"], sample[1]["RC7"]) == (0, 0, 0)), None)
    if tx_active is None:
        raise AssertionError(f"{trip_name} trip did not follow an active TX state")
    active_ms = (trip[0] - tx_active[0]) * SECONDS_PER_INSTRUCTION * 1000
    if active_ms < 500:
        raise AssertionError(f"{trip_name} trip occurred after only {active_ms:.1f}ms of TX")
    print(f"TX active before {trip_name} trip: {active_ms:.1f}ms")
    shutdown_done = next((sample for sample in samples
                          if sample[2]["g_fault_latched"] == "true" and
                          (sample[1]["RC5"], sample[1]["RC6"], sample[1]["RC7"]) == (1, 1, 1) and
                          block_reason(sample[2]) == expected_reason), None)
    if shutdown_done is None or (shutdown_done[1]["RC5"], shutdown_done[1]["RC6"], shutdown_done[1]["RC7"]) != (1, 1, 1):
        raise AssertionError("fault did not raise RELAYS and TX_BIAS after five milliseconds")
    if trip_name == "CURRENT":
        if not any(sample[3]["RB1"] == 0.0 for sample in samples[samples.index(trip) + 1:]):
            raise AssertionError("current sensor did not fall to zero during the trip shutdown")
    if trip_name == "TEMPERATURE":
        post_shutdown = samples[samples.index(shutdown_done):]
        if any((sample[1]["RC5"], sample[1]["RC6"], sample[1]["RC7"]) != (1, 1, 1)
               for sample in post_shutdown if sample[2]["g_fault_latched"] == "true"):
            raise AssertionError("temperature trip outputs did not remain high until recovery")
        recovered = next((sample for sample in samples[samples.index(shutdown_done) + 1:]
                          if sample[2]["g_fault_latched"] == "false" and
                          sample[2]["g_sequence_stage"] == "3"), None)
        if recovered is None or (recovered[1]["RC5"], recovered[1]["RC6"], recovered[1]["RC7"]) != (0, 0, 0):
            raise AssertionError("temperature recovery did not re-enter the active TX sequence")
        print("TEMP RECOVERED: TX sequence resumed after hysteresis")
    elif shutdown_done[2]["g_fault_latched"] != "true":
        raise AssertionError(f"{trip_name} fault unexpectedly recovered")
    else:
        recovered = next((sample for sample in samples[samples.index(shutdown_done) + 1:]
                          if sample[2]["g_fault_latched"] == "false" and
                          sample[2]["g_sequence_stage"] == "3"), None)
        if recovered is None:
            recovery_trace = [
                (sample[2].get("g_ptt_active"),
                 sample[2].get("g_fault_latched"),
                 sample[2].get("g_trip_reason"),
                 sample[2].get("g_sequence_stage"),
                 sample[2].get("g_fc_status.frequency_khz"),
                 sample[2].get("g_fc_status.current_band"),
                 sample[2].get("g_fc_status.band_locked"),
                 (sample[1]["RC5"], sample[1]["RC6"], sample[1]["RC7"]),
                 (sample[3]["RA0"], sample[3]["RA1"]))
                for sample in samples[samples.index(shutdown_done):]
            ]
            print(f"SWR_DEBUG {trip_name} recovery_trace={recovery_trace}", flush=True)
            raise AssertionError(f"{trip_name} did not clear and re-enter TX after a PTT re-arm")
        if trip_name == "CURRENT" and recovered[3]["RB1"] > 2.95:
            raise AssertionError("current re-arm exceeded the 10A limit")
        print(f"{trip_name} cleared by PTT re-arm; TX sequence resumed")
    if trip_name == "TEMPERATURE" and trip[3]["RA5"] < 4.0:
        raise AssertionError("temperature ADC input did not rise above 4V")
    print(f"ADC voltages at {trip_name}: " +
          ", ".join(f"{pin}={trip[3][pin]:.3f}V" for pin in ADC_PINS))
    print(f"TRIP: {trip_name} ({expected_reason})")


def validate_swr1_1p5(samples) -> None:
    if any((block_reason(sample[2]) or "").startswith("FAULT:") for sample in samples):
        raise AssertionError("1.5:1 SWR incorrectly tripped")
    active = [sample for sample in samples
              if sample[2]["g_sequence_stage"] == "3" and
              (sample[1]["RC5"], sample[1]["RC6"], sample[1]["RC7"]) == (0, 0, 0)]
    if not active:
        raise AssertionError("1.5:1 SWR did not remain in active TX")
    active_ms = (samples[-1][0] - active[0][0]) * SECONDS_PER_INSTRUCTION * 1000
    if active_ms < 500:
        raise AssertionError(f"1.5:1 SWR was active for only {active_ms:.1f}ms")
    print(f"SWR1 1.50:1 at 2.000kW PEP: no trip; TX remained active for {active_ms:.1f}ms")


def parse_trace(output: str):
    """Walks the mdb transcript in order, tracking cumulative instruction count and
    each pin's/variable's most-recently-printed value, sampling a full snapshot every
    time all pins and state variables have been reprinted (i.e. once per Stepi block)."""
    samples = []
    instr_count = 0
    pending = {}
    pending_adc = {}
    pending_voltages = {}
    state_pending = {}
    awaiting_var = None
    for raw_line in output.splitlines():
        line = raw_line.strip()
        m_stepi = STEPI_RE.match(line)
        if m_stepi:
            instr_count += int(m_stepi.group(1))
            continue
        if awaiting_var is not None:
            if line:
                state_pending[awaiting_var] = line
                awaiting_var = None
            continue
        m_var = VAR_NAME_RE.match(line)
        if m_var:
            awaiting_var = m_var.group(1)
            continue
        m = PRINT_RE.match(line)
        if m:
            pin, level, volts = m.groups()
            pending[pin] = 1 if level == "HIGH" or (volts is not None and float(volts) >= 2.5) else 0
            if pin in ADC_PINS:
                pending_adc[pin] = 1
                pending_voltages[pin] = float(volts) if volts is not None else (5.0 if level == "HIGH" else 0.0)
        if (len(pending) == len(PINS) + len(ADC_PINS) and
            len(pending_adc) == len(ADC_PINS) and len(state_pending) == len(STATE_VARS)):
            samples.append((instr_count, dict(pending), dict(state_pending), dict(pending_voltages)))
            pending.clear()
            pending_adc.clear()
            pending_voltages.clear()
            state_pending.clear()
    return samples


def write_trace_csv(samples, trace_name, csv_dir):
    csv_path = csv_dir / f"{trace_name}.csv"
    with open(csv_path, "w") as f:
        f.write("time_s," + ",".join(PIN_LABELS[p] for p in PINS) +
                "," + ",".join(f"ADC_{pin}_V" for pin in ADC_PINS) +
                ",g_ptt_active,g_sequence_stage,g_state,block_reason\n")
        for instr_count, vals, state, adc_voltages in samples:
            t = instr_count * SECONDS_PER_INSTRUCTION
            reason = block_reason(state) or ""
            f.write(f"{t:.6f}," + ",".join(str(vals[p]) for p in PINS) +
                    "," + ",".join(f"{adc_voltages[pin]:.3f}" for pin in ADC_PINS) +
                    f",{state['g_ptt_active']},{state['g_sequence_stage']},{state['g_state']},{reason}\n")
    return csv_path


def assign_event_label_lanes(events, x_min, x_max):
    lanes = []
    placed = []
    span = max(1.0, x_max - x_min)
    for event_time, event_label, color in sorted(events, key=lambda event: event[0]):
        text = f"{event_label} @ {event_time:.1f} ms"
        half_width = max(span * 0.035, len(text) * span / 180.0)
        start = event_time - half_width
        end = event_time + half_width
        for lane_index, lane_end in enumerate(lanes):
            if start > lane_end:
                lanes[lane_index] = end
                break
        else:
            lane_index = len(lanes)
            lanes.append(end)
        placed.append((event_time, text, color, lane_index))
    return placed, len(lanes)


def draw_event_labels_after_layout(fig, axes, events, x_min, x_max):
    placed, lane_count = assign_event_label_lanes(events, x_min, x_max)
    if not placed:
        return 0
    ax = axes[0]
    fig.text(0.5, 0.948,
             "Stacked lanes mean events share the same or nearby timestamp; red shading marks active lockout windows.",
             ha="center", va="top", fontsize=7, color="#546e7a")
    y_start = 0.915
    y_step = 0.026
    for event_time, text, color, lane_index in placed:
        x_display = ax.transData.transform((event_time, 0))[0]
        x_figure = fig.transFigure.inverted().transform((x_display, 0))[0]
        x_fraction = (event_time - x_min) / max(1.0, x_max - x_min)
        align = "left" if x_fraction < 0.08 else "right" if x_fraction > 0.92 else "center"
        fig.text(x_figure, y_start - lane_index * y_step, text,
                 ha=align, va="bottom", fontsize=7, color=color)
    return lane_count


def trace_plot_top(lane_count):
    return max(0.55, 0.88 - lane_count * 0.03)


def write_trace_graph(samples, trip_name, trace_name, graph_dir):
    try:
        import matplotlib.pyplot as plt
    except ImportError:
        return None
    times = [sample[0] * SECONDS_PER_INSTRUCTION * 1000 for sample in samples]
    graph_adc_pins = TRIP_ADC_PINS.get(trip_name, []) if trip_name else []
    graph_rows = [("digital", pin) for pin in PINS] + [("adc", pin) for pin in graph_adc_pins]
    fig, axes = plt.subplots(len(graph_rows), 1, sharex=True,
                             figsize=(10, max(6, len(graph_rows) * 1.25)))
    axes = list(axes) if hasattr(axes, "__len__") else [axes]
    trip_index = next((index for index, sample in enumerate(samples)
                       if trip_name in TRIP_NAMES and block_reason(sample[2]) == f"FAULT: {trip_name}"), None)
    trip_time = times[trip_index] if trip_index is not None else None
    shutdown_complete_time = times[next((index for index, sample in enumerate(samples)
                                         if trip_name in TRIP_NAMES and
                                         index >= trip_index and
                                         sample[1]["RC5"] == 1 and
                                         sample[1]["RC6"] == 1 and
                                         sample[1]["RC7"] == 1), trip_index)] if trip_index is not None else None
    complete_index = next((index for index, sample in enumerate(samples)
                           if sample[2]["g_ptt_complete_display_active"] == "true" and
                           (sample[1]["RC5"], sample[1]["RC6"], sample[1]["RC7"]) == (0, 0, 0)), None)
    lifecycle = [(times[0], "LCD: STARTUP")]
    ptt_index = next((index for index, sample in enumerate(samples) if sample[2]["g_ptt_active"] == "true"), None)
    if ptt_index is not None:
        lifecycle.append((times[ptt_index], "LCD: PTT REQ"))
    if complete_index is not None:
        lifecycle.append((times[complete_index], "LCD: PTT_COMPLETE"))
        restored_index = next((index for index, sample in enumerate(samples)
                               if index > complete_index and
                               sample[2]["g_transient_menu_display"] == "false"), None)
        if restored_index is not None:
            lifecycle.append((times[restored_index], "LCD: RESTORED USER PAGE"))
    if trip_time is not None:
        lifecycle.append((trip_time, f"LCD: TRIP {trip_name}"))
    for ax, (kind, pin) in zip(axes, graph_rows):
        if kind == "digital":
            ax.step(times, [sample[1][pin] for sample in samples], where="post")
            ax.set_ylim(-0.2, 1.2)
            ax.set_yticks([0, 1])
            label = PIN_LABELS[pin]
        else:
            values = [sample[3][pin] for sample in samples]
            ax.plot(times, values, drawstyle="steps-post")
            ax.set_ylim(-0.2, 5.2)
            label = f"ADC {ADC_LABELS[pin]}"
            if trip_index is not None:
                ax.annotate(f"{values[trip_index]:.3f} V", (times[trip_index], values[trip_index]),
                            xytext=(8, 4), textcoords="offset points", fontsize=8)
        ax.set_ylabel(f"{pin}\n{label}", rotation=0, labelpad=42, va="center")
        ax.grid(True, alpha=0.3)
    reasons = [block_reason(sample[2]) for sample in samples]
    span_start = 0
    span_reason = reasons[0]
    spans = []
    for index, reason in enumerate(reasons[1:], 1):
        if reason != span_reason:
            if span_reason:
                spans.append((times[span_start], times[index], span_reason))
            span_start, span_reason = index, reason
    if span_reason:
        spans.append((times[span_start], times[-1], span_reason))
    for start, end, reason in spans:
        for ax in axes:
            ax.axvspan(start, end, color="red", alpha=0.12)
    for marker_time, marker_label in lifecycle:
        axes[0].axvline(marker_time, color="steelblue", linestyle="-.", alpha=0.45)
    if trip_time is not None:
        axes[0].axvline(trip_time, color="red", linestyle="--", alpha=0.6)
    events = [(time, label, "steelblue") for time, label in lifecycle]
    events += [(span_start, reason, "red") for span_start, _end, reason in spans]
    if trip_time is not None:
        events += [(trip_time, "TX_VCC HIGH (immediate)", "red"),
                   (shutdown_complete_time, "RELAYS HIGH (+5 ms)", "red"),
                   (shutdown_complete_time, "TX_BIAS HIGH (+5 ms)", "red")]
    axes[0].set_xlim(0, times[-1])
    axes[-1].set_xlabel("time (ms, approx)")
    title = f"PTT sequencing with {trip_name} trip (simulated)" if trip_name else "PTT assert/release sequencing (simulated)"
    fig.suptitle(title, y=0.985)
    _placed, lane_count = assign_event_label_lanes(events, times[0], times[-1])
    fig.tight_layout(rect=(0, 0, 1, trace_plot_top(lane_count)))
    draw_event_labels_after_layout(fig, axes, events, times[0], times[-1])
    graph_path = graph_dir / f"{trace_name}.png"
    fig.savefig(graph_path, dpi=120)
    plt.close(fig)
    return graph_path


def main():
    test_mode = "--test" in sys.argv[1:]
    if "--quick-bands" in sys.argv[1:]:
        BAND_TESTS[:] = [("40m", 7000, 3)]
    trip_name = "TEMPERATURE" if "--temperature-trip" in sys.argv[1:] else None
    if "--swr1-1p5" in sys.argv[1:]:
        trip_name = "SWR1_1P5"
    if "--trip" in sys.argv[1:]:
        trip_name = sys.argv[sys.argv.index("--trip") + 1].upper()
    if trip_name is not None and trip_name not in TRIP_NAMES | NON_TRIP_NAMES:
        sys.exit(f"error: unknown trip {trip_name}")
    temperature_trip = trip_name == "TEMPERATURE"
    if "--suite" in sys.argv[1:]:
        scenario_names = [None, "TEMPERATURE", "SWR1", "SWR2", "HWFAULT",
                          "CURRENT", "OVERDRIVE", "DRAIN", "SWR1_1P5", "FREQ_CTR",
                          "FREQ_CTR_FAIL"]
        if "--quick-bands" in sys.argv[1:]:
            scenario_names = [None, "FREQ_CTR", "FREQ_CTR_FAIL"]
        first_script = build_script()
        suite_lines = first_script.splitlines()[:-1]
        for index, scenario in enumerate(scenario_names[1:], 1):
            scenario_lines = build_script(trip_name=scenario).splitlines()
            suite_lines.append("reset")
            suite_lines.extend(scenario_lines[3:-1])
        raw_output = run_mdb(mdb_path=find_mdb(), script="\n".join(suite_lines + ["quit"]))
        groups = [(index, parse_trace(chunk)) for index, chunk in enumerate(raw_output.split("Resetting SFRs"))]
        groups = [(marker, scenario_samples) for marker, scenario_samples in groups if scenario_samples]
        if len(groups) != len(scenario_names):
            raise AssertionError(f"suite produced {len(groups)} scenarios, expected {len(scenario_names)}")
        validate_sequence(groups[0][1])
        validate_frequency_ready(groups[0][1], scenario_names[0])
        for scenario, (_, scenario_samples) in zip(scenario_names[1:], groups[1:]):
            if scenario == "FREQ_CTR_FAIL":
                validate_freq_ctr_failure(scenario_samples)
            else:
                validate_frequency_ready(scenario_samples, scenario)
            if scenario == "SWR1_1P5":
                validate_swr1_1p5(scenario_samples)
            elif scenario == "FREQ_CTR":
                validate_freq_ctr(scenario_samples, scenario)
            elif scenario == "FREQ_CTR_FAIL":
                pass
            else:
                validate_trip(scenario_samples, scenario)
        # Band-selection safety invariants (docs/first-dit-band-detection.md) over every
        # scenario: the LPF relays must never move while the amplifier is keyed, the amplifier
        # must never be keyed on a band that is not locked, and the band relays must always be
        # switched before the T/R relay closes (never hot-switch the band relay).
        for scenario, (_, scenario_samples) in zip(scenario_names, groups):
            label = scenario or "PTT_BASE"
            for line in invariants.validate_keyed_band_invariants(scenario_samples, label):
                print(line)
            for line in invariants.validate_band_changes_are_cold(scenario_samples, label):
                print(line)
            for line in invariants.validate_t_r_closes_only_after_band_settle(
                    scenario_samples, label):
                print(line)
        out_dir = REPO_ROOT / "_build" / "My_Pic_Project" / "sim"
        csv_dir = out_dir / "csv"
        graph_dir = out_dir / "graphs"
        csv_dir.mkdir(parents=True, exist_ok=True)
        graph_dir.mkdir(parents=True, exist_ok=True)
        for scenario, (_, scenario_samples) in zip(scenario_names, groups):
            if scenario in TRIP_NAMES:
                trace_name = f"{scenario.lower()}_trip_trace"
            else:
                trace_name = f"{scenario.lower()}_trace" if scenario else "ptt_trace"
            write_trace_csv(scenario_samples, trace_name, csv_dir)
            write_trace_graph(scenario_samples, scenario, trace_name, graph_dir)
        print(f"PTT suite passed: {len(scenario_names)} scenarios in one MDB session")
        return
    if not ELF_PATH.exists():
        sys.exit(f"error: {ELF_PATH} not found - build firmware first (build_firmware.ps1/.sh)")
    mdb_path = find_mdb()
    script = build_script(trip_name=trip_name)
    output = run_mdb(mdb_path, script)
    samples = parse_trace(output)
    if not samples:
        sys.exit("error: no samples parsed from mdb output - dumping raw output:\n" + output[-4000:])
    if test_mode:
        validate_sequence(samples)
        print("PTT sequencing test passed")
    if trip_name:
        if trip_name in TRIP_NAMES:
            validate_trip(samples, trip_name)
        else:
            validate_swr1_1p5(samples)

    out_dir = REPO_ROOT / "_build" / "My_Pic_Project" / "sim"
    csv_dir = out_dir / "csv"
    graph_dir = out_dir / "graphs"
    csv_dir.mkdir(parents=True, exist_ok=True)
    graph_dir.mkdir(parents=True, exist_ok=True)
    trace_name = f"{trip_name.lower()}_trip_trace" if trip_name else "ptt_trace"
    csv_path = csv_dir / f"{trace_name}.csv"
    with open(csv_path, "w") as f:
        f.write("time_s," + ",".join(PIN_LABELS[p] for p in PINS) +
            "," + ",".join(f"ADC_{pin}_V" for pin in ADC_PINS) +
            ",g_ptt_active,g_sequence_stage,g_state,block_reason\n")
        for instr_count, vals, state, adc_voltages in samples:
            t = instr_count * SECONDS_PER_INSTRUCTION
            reason = block_reason(state) or ""
            f.write(f"{t:.6f}," + ",".join(str(vals[p]) for p in PINS) +
                "," + ",".join(f"{adc_voltages[pin]:.3f}" for pin in ADC_PINS) +
                f",{state['g_ptt_active']},{state['g_sequence_stage']},{state['g_state']},{reason}\n")
    print(f"Wrote {csv_path} ({len(samples)} samples)")

    # Print console FAULT/blocking-reason transitions so "why can't PTT key up" is obvious
    # without having to read the plot.
    last_reason = object()
    for instr_count, _vals, state, _adc_voltages in samples:
        reason = block_reason(state)
        if reason != last_reason:
            t = instr_count * SECONDS_PER_INSTRUCTION * 1000
            print(f"t={t:8.2f}ms  {reason if reason else 'PTT OK (no block)'}")
            last_reason = reason

    try:
        import matplotlib.pyplot as plt
    except ImportError:
        print("matplotlib not installed; skipping PNG (pip install matplotlib)")
        return

    times = [s[0] * SECONDS_PER_INSTRUCTION * 1000 for s in samples]  # ms
    reasons = [block_reason(s[2]) for s in samples]

    # Contiguous [start, end, reason] spans where PTT/TX is blocked, for shading/labeling.
    block_spans = []
    span_start = None
    span_reason = None
    for t, reason in zip(times, reasons):
        if reason != span_reason:
            if span_reason is not None:
                block_spans.append((span_start, t, span_reason))
            span_start, span_reason = t, reason
    if span_reason is not None:
        block_spans.append((span_start, times[-1], span_reason))

    graph_adc_pins = TRIP_ADC_PINS.get(trip_name, []) if trip_name else []
    graph_rows = [("digital", pin) for pin in PINS] + [("adc", pin) for pin in graph_adc_pins]
    fig, axes = plt.subplots(len(graph_rows), 1, sharex=True,
                             figsize=(10, max(6, len(graph_rows) * 1.25)))
    axes = list(axes) if hasattr(axes, "__len__") else [axes]
    trip_time = None
    shutdown_complete_time = None
    trip_index = None
    if trip_name in TRIP_NAMES:
        trip_index = next(index for index, sample in enumerate(samples)
                          if block_reason(sample[2]) == f"FAULT: {trip_name}")
        trip_time = times[trip_index]
        shutdown_complete_time = times[next(index for index, sample in enumerate(samples)
                                            if sample[2]["g_trip_shutdown_active"] == "false" and
                                            block_reason(sample[2]) == f"FAULT: {trip_name}")]
    lifecycle = [(times[0], "LCD: STARTUP")]
    ptt_index = next((index for index, sample in enumerate(samples)
                      if sample[2]["g_ptt_active"] == "true"), None)
    if ptt_index is not None:
        lifecycle.append((times[ptt_index], "LCD: PTT REQ"))
    complete_index = next((index for index, sample in enumerate(samples)
                           if sample[2]["g_ptt_complete_display_active"] == "true" and
                           (sample[1]["RC5"], sample[1]["RC6"], sample[1]["RC7"]) == (0, 0, 0)), None)
    if complete_index is not None:
        lifecycle.append((times[complete_index], "LCD: PTT_COMPLETE"))
    if trip_time is not None:
        lifecycle.append((trip_time, f"LCD: TRIP {trip_name}"))
    restored_index = next((index for index, sample in enumerate(samples)
                           if complete_index is not None and index > complete_index and
                           sample[2]["g_transient_menu_display"] == "false"), None)
    if restored_index is not None:
        lifecycle.append((times[restored_index], "LCD: RESTORED USER PAGE"))
    for ax, (kind, pin) in zip(axes, graph_rows):
        if kind == "digital":
            values = [s[1][pin] for s in samples]
            ax.step(times, values, where="post")
            ax.set_ylim(-0.2, 1.2)
            ax.set_yticks([0, 1])
            label = PIN_LABELS[pin]
        else:
            values = [s[3][pin] for s in samples]
            ax.plot(times, values, drawstyle="steps-post")
            ax.set_ylim(-0.2, 5.2)
            label = f"ADC {ADC_LABELS[pin]}"
            if trip_index is not None:
                ax.annotate(f"{values[trip_index]:.3f} V", (trip_time, values[trip_index]),
                            xytext=(8, 4), textcoords="offset points", fontsize=8)
        ax.set_ylabel(f"{pin}\n{label}", rotation=0, labelpad=42, va="center")
        ax.grid(True, alpha=0.3)
        for start, end, reason in block_spans:
            ax.axvspan(start, end, color="red", alpha=0.12)
        if trip_name in TRIP_NAMES:
            ax.axvline(trip_time, color="red", linestyle="--", alpha=0.6)
            ax.axvline(shutdown_complete_time, color="orange", linestyle=":", alpha=0.7)
    for marker_time, marker_label in lifecycle:
        axes[0].axvline(marker_time, color="steelblue", linestyle="-.", alpha=0.45)
    events = [(time, label, "steelblue") for time, label in lifecycle]
    events += [(start, reason, "red") for start, _end, reason in block_spans]
    if trip_name in TRIP_NAMES:
        events += [(trip_time, "TX_VCC HIGH (immediate)", "red"),
                   (shutdown_complete_time, "RELAYS HIGH (+5 ms)", "red"),
                   (shutdown_complete_time, "TX_BIAS HIGH (+5 ms)", "red")]
    axes[0].set_xlim(0, times[-1])
    axes[-1].set_xlabel("time (ms, approx)")
    title = ("PTT sequencing with SWR1 1.5:1 no-trip (simulated)" if trip_name == "SWR1_1P5"
             else f"PTT sequencing with {trip_name} trip (simulated)" if trip_name
             else "PTT assert/release sequencing (simulated)")
    fig.suptitle(title, y=0.985)
    _placed, lane_count = assign_event_label_lanes(events, times[0], times[-1])
    fig.tight_layout(rect=(0, 0, 1, trace_plot_top(lane_count)))
    draw_event_labels_after_layout(fig, axes, events, times[0], times[-1])
    png_path = graph_dir / f"{trace_name}.png"
    fig.savefig(png_path, dpi=120)
    print(f"Wrote {png_path}")
if __name__ == "__main__":
    main()

