#!/usr/bin/env python3
# Code generated by MCHP Chatbot
"""Captures a scope-like trace of PTT/TX/TX_VCC/TX_BIAS pins across a PTT assert/release
cycle by single-stepping the MPLAB X `mdb` simulator and polling pin state at fixed
instruction intervals, then renders a logic-analyzer-style PNG.

Timing is approximate: instruction counts are converted to seconds assuming one
instruction cycle per Stepi step at _XTAL_FREQ/4 (see firmware/include/pin_map.h).
This is close enough to see the shape/order of the sequencer delays, not a cycle-exact
measurement.

Usage:
    python tools/simulate/trace_ptt_sequence.py
    python tools/simulate/trace_ptt_sequence.py --test
    python tools/simulate/trace_ptt_sequence.py --temperature-trip
    python tools/simulate/trace_ptt_sequence.py --trip SWR1
    python tools/simulate/trace_ptt_sequence.py --swr1-1p5
Requires: MPLAB X IDE (mdb), and matplotlib (pip install matplotlib) for the PNG output.
"""
import re
import subprocess
import sys
import tempfile
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent.parent
HEX_PATH = REPO_ROOT / "out" / "My_Pic_Project" / "default.hex"
# Loaded instead of the .hex so mdb can resolve C variable names (debug symbols).
ELF_PATH = REPO_ROOT / "out" / "My_Pic_Project" / "default.elf"
DEVICE = "PIC16F18855"

# Firmware globals that explain why PTT/TX may be blocked (see main.c).
STATE_VARS = [
    "g_startup_inhibit", "g_comparator_reset_active", "g_fault_latched", "g_trip_reason",
    "g_ptt_active", "g_sequence_stage", "g_state", "g_trip_shutdown_active",
    "g_ptt_complete_display_active", "g_transient_menu_display"
]
TRIP_REASON_BITS = [
    (0x01, "SWR1"),
    (0x02, "SWR2"),
    (0x04, "HWFAULT"),
    (0x08, "CURRENT"),
    (0x10, "TEMPERATURE"),
    (0x20, "OVERDRIVE"),
    (0x40, "DRAIN"),
]
XTAL_FREQ = 32_000_000
SECONDS_PER_INSTRUCTION = 4 / XTAL_FREQ  # approx; 1 instruction cycle = 4 osc clocks

STEP_SIZE = 2000
PHASES = [
    # PTT idle (inactive, active-low), coarsely stepped through the bulk of
    # the ~1s startup-inhibit wait (see g_startup_elapsed_ms in main.c).
    ("steady_coarse", "5v", 22, 180000),  # ~495ms
    # Finer-grained stepping across the 1000ms boundary (with margin for
    # init overhead: lcd_init/adc_init delays before the main loop's ms
    # clock starts) so the ~10ms SETTLE (comparator reset) pulse isn't
    # skipped between samples.
    ("steady_mid", "5v", 402, 20000),  # ~495ms -> ~1500ms, 2.5ms/sample
    ("asserted", "0v", 300, STEP_SIZE),  # PTT pressed; covers both ~20ms sequencer delays
    ("released", "5v", 100, STEP_SIZE),  # PTT released again
]
PINS = ["RC1", "RC0", "RC5", "RC6", "RC7"]
PIN_LABELS = {"RC1": "SETTLE", "RC0": "PTT", "RC5": "RELAYS", "RC6": "TX_VCC", "RC7": "TX_BIAS"}
ADC_PINS = ["RA0", "RA1", "RA2", "RA3", "RA5", "RB1", "RB2", "RB3"]
SCENARIO_MARKER_PIN = "RB6"
ADC_LABELS = {
    "RA0": "SWR1 FWD", "RA1": "SWR1 REF", "RA2": "SWR2 FWD", "RA3": "SWR2 REF",
    "RA5": "TEMPERATURE", "RB1": "CURRENT", "RB2": "OVERDRIVE", "RB3": "DRAIN"
}
TRIP_ADC_PINS = {
    "SWR1": ["RA0", "RA1"], "SWR2": ["RA2", "RA3"],
    "SWR1_1P5": ["RA0", "RA1"],
    "TEMPERATURE": ["RA5"], "CURRENT": ["RB1"],
    "OVERDRIVE": ["RB2"], "DRAIN": ["RB3"], "HWFAULT": []
}
TRIP_NAMES = {"SWR1", "SWR2", "HWFAULT", "CURRENT", "OVERDRIVE", "DRAIN", "TEMPERATURE"}
NON_TRIP_NAMES = {"SWR1_1P5"}


def find_mdb() -> Path:
    candidates = sorted(Path("C:/Program Files/Microchip/MPLABX").glob("*/mplab_platform/bin/mdb.bat"))
    if not candidates:
        candidates = sorted(Path("/Applications/microchip/mplabx").glob("*/mplab_platform/bin/mdb.sh"))
    if not candidates:
        sys.exit("error: mdb not found. Install MPLAB X IDE.")
    return candidates[-1]


# Code generated by MCHP Chatbot
def build_script(trip_name=None, marker=None) -> str:
    temperature_trip = trip_name == "TEMPERATURE"
    lines = [f"device {DEVICE}", "hwtool sim", f"program {ELF_PATH}"]
    if marker is not None:
        lines.append(f"write pin {SCENARIO_MARKER_PIN} {marker}v")
    # --- Setup: Set all analog and relevant inputs to safe values ---
    lines += [
        "write pin RA0 0v", "write pin RA1 0v", "write pin RA2 0v", "write pin RA3 0v",
        "write pin RA5 2.5v", "write pin RB1 0v", "write pin RB2 0v", "write pin RB3 0v", "write pin RB4 0v"
    ]

    def sample():
        for pin in PINS:
            lines.append(f"print pin {pin}")
        for pin in ADC_PINS:
            lines.append(f"print pin {pin}")
        lines.append(f"print pin {SCENARIO_MARKER_PIN}")
        for var in STATE_VARS:
            lines.append(f"print {var}")

    if trip_name == "SWR1_1P5":
        lines[3:5] = ["write pin RA0 5.000v", "write pin RA1 0.200v"]
    if not temperature_trip:
        # --- Briefly assert PTT during startup; it must have no effect while inhibited ---
        lines.append("write pin RC0 0v")
        for _ in range(5):  # 50 ms while startup inhibit is active
            lines.append("Stepi 80000")
            sample()
        lines.append("write pin RC0 5v")

    # --- Finish the settle (startup inhibit) period: 1100ms total ---
    for _ in range(105 if not temperature_trip else 110):
        lines.append("Stepi 80000")  # 10 ms per print
        sample()
    # --- Assert PTT (pull RC0 low), triggering SETTLE high for 10 ms ---
    lines.append("write pin RC0 0v")
    # Fine-grained steps to catch SETTLE high pulse (comparator reset)
    for _ in range(12):  # ~12 ms sampled every 1 ms
        lines.append("Stepi 8000")
        sample()
    # Continue simulation for sequencer actions (TX, TX_VCC, etc), 200 ms more
    for _ in range(10 if temperature_trip else 40):
        lines.append("Stepi 40000")
        sample()
    # Hold PTT low for 500 ms before releasing it.
    for _ in range(100):
        lines.append("Stepi 40000")
        sample()
    if trip_name == "SWR1_1P5":
        lines.append("write pin RA0 5.000v")
        lines.append("write pin RA1 0.200v")
        for _ in range(20):  # prove 1.5:1 remains in TX for another 100ms
            lines.append("Stepi 40000")
            sample()
        lines.append("quit")
        return "\n".join(lines)
    if trip_name and not temperature_trip:
        if trip_name == "CURRENT":
            for step in range(1, 21):
                current_a = 20 + step * 1.5
                voltage = 2.5 + (current_a / 70.0) * 2.5
                lines.append(f"write pin RB1 {voltage:.3f}v")
                if current_a >= 41:
                    for _ in range(10):  # capture the five-millisecond trip shutdown
                        lines.append("Stepi 8000")
                        sample()
                    break
                lines.append("Stepi 400000")  # 50ms per ramp step
                sample()
            lines.append("write pin RB1 0.000v")  # sensor output falls when TX is removed
            for _ in range(10):
                lines.append("Stepi 40000")
                sample()
            safe_inputs = {"CURRENT": [("RB1", 2.857)]}  # 10A maximum on the next PTT attempt
        else:
            safe_inputs = None
        trip_inputs = {
            "SWR1": [("RA0", 2.500), ("RA1", 0.750)],
            "SWR2": [("RA2", 2.500), ("RA3", 0.400)],
            "HWFAULT": [("RB4", 5.000)],
            "CURRENT": [("RB1", 5.000)],
            "OVERDRIVE": [("RB2", 5.000)],
            "DRAIN": [("RB3", 5.000)],
        }
        if trip_name != "CURRENT":
            for pin, voltage in trip_inputs[trip_name]:
                lines.append(f"write pin {pin} {voltage:.3f}v")
            for _ in range(10):
                lines.append("Stepi 8000")
                sample()
            for _ in range(10):  # show the latched trip state for another 50ms
                lines.append("Stepi 400000")
                sample()
        if safe_inputs is None:
            safe_inputs = {
            "SWR1": [("RA0", 0.0), ("RA1", 0.0)],
            "SWR2": [("RA2", 0.0), ("RA3", 0.0)],
            "HWFAULT": [("RB4", 0.0)], "CURRENT": [("RB1", 0.0)],
            "OVERDRIVE": [("RB2", 0.0)], "DRAIN": [("RB3", 0.0)]
            }
        for pin, voltage in safe_inputs[trip_name]:
            lines.append(f"write pin {pin} {voltage:.3f}v")
        lines.append("write pin RC0 5v")
        lines.append("Stepi 40000")
        sample()
        lines.append("write pin RC0 0v")
        for _ in range(50):
            lines.append("Stepi 8000")
            sample()
        lines.append("quit")
        return "\n".join(lines)
    if temperature_trip:
        # Raise the temperature stimulus from 2.5V to 5V over one simulated second.
        for step in range(1, 21):
            voltage = 2.5 + step * 0.125
            lines.append(f"write pin RA5 {voltage:.3f}v")
            if step < 20:
                lines.append("Stepi 400000")  # 50ms per ramp step
                sample()
            else:
                for _ in range(10):  # capture the five-millisecond shutdown sequence
                    lines.append("Stepi 8000")
                    sample()
        for _ in range(10):  # show the latched trip state for another 500ms
            lines.append("Stepi 400000")
            sample()
        # Lower the temperature stimulus back to 2.5V over two simulated seconds.
        for step in range(19, -1, -1):
            voltage = 2.5 + step * 0.125
            lines.append(f"write pin RA5 {voltage:.3f}v")
            lines.append("Stepi 400000")  # 50ms per recovery-ramp step
            sample()
        lines.append("quit")
        return "\n".join(lines)
    # --- Release PTT (RC0 back high): relays open, then VCC, then bias ---
    lines.append("write pin RC0 5v")
    for _ in range(40):  # 5 ms steps, 40x5 = 200 ms
        lines.append("Stepi 40000")
        sample()
    lines.append("quit")
    return "\n".join(lines)

def run_mdb(mdb_path: Path, script: str) -> str:
    with tempfile.NamedTemporaryFile("w", suffix=".mdb", delete=False) as f:
        f.write(script)
        script_path = f.name
    try:
        result = subprocess.run(
            [str(mdb_path), script_path], capture_output=True, text=True, check=False
        )
        return result.stdout + result.stderr
    finally:
        Path(script_path).unlink(missing_ok=True)


PRINT_RE = re.compile(r"^(R[A-Z]\d+)\s+\S+\s+(?:(HIGH|LOW)|([\d.]+)V)", re.MULTILINE)
STEPI_RE = re.compile(r"^Stepi\s+(\d+)")
VAR_NAME_RE = re.compile(r"^(g_\w+)=$")


def block_reason(state: dict) -> str | None:
    """Returns a human-readable reason PTT/TX is blocked, or None if it isn't."""
    if state.get("g_startup_inhibit") == "true":
        return "STARTUP INHIBIT"
    if state.get("g_comparator_reset_active") == "true":
        return "PTT_RESET_PULSE"
    if state.get("g_fault_latched") == "true":
        try:
            reason_bits = int(state.get("g_trip_reason", "0"))
        except ValueError:
            reason_bits = 0
        names = [name for bit, name in TRIP_REASON_BITS if reason_bits & bit]
        return "FAULT: " + "+".join(names) if names else "FAULT: UNKNOWN"
    return None


def validate_sequence(samples) -> None:
    """Fail when startup inhibit or either PTT sequencing direction is wrong."""
    startup_samples = [sample for sample in samples if sample[2]["g_startup_inhibit"] == "true"]
    if not any(sample[1]["RC0"] == 0 and all(sample[1][pin] == 1 for pin in ("RC5", "RC6", "RC7"))
               for sample in startup_samples):
        raise AssertionError("PTT was not ignored during startup inhibit")

    active_samples = [sample for sample in samples
                      if sample[2]["g_ptt_active"] == "true" and sample[2]["g_sequence_stage"] == "3"]
    if not active_samples:
        raise AssertionError("PTT active sequence did not reach stage 3")
    active = active_samples[0][1]
    if (active["RC5"], active["RC6"], active["RC7"]) != (0, 0, 0):
        raise AssertionError("active sequence did not drive RELAYS, TX_VCC, TX_BIAS low")
    complete_display = next((sample for sample in samples
                             if sample[2]["g_ptt_complete_display_active"] == "true"), None)
    if complete_display is None or (complete_display[1]["RC5"], complete_display[1]["RC6"], complete_display[1]["RC7"]) != (0, 0, 0):
        raise AssertionError("PTT COMPLETE was displayed before all TX outputs went low")

    release_samples = [sample for sample in samples if sample[2]["g_ptt_active"] == "false"]
    release_stage4 = next((sample for sample in release_samples if sample[2]["g_sequence_stage"] == "4"), None)
    release_stage5 = next((sample for sample in release_samples if sample[2]["g_sequence_stage"] == "5"), None)
    release_done = next((sample for sample in release_samples if sample[2]["g_sequence_stage"] == "0"
                         and sample[1]["RC5"] == 1 and sample[1]["RC6"] == 1 and sample[1]["RC7"] == 1), None)
    if release_stage4 is None or release_stage4[1]["RC5"] != 1 or release_stage4[1]["RC6"] != 0 or release_stage4[1]["RC7"] != 0:
        raise AssertionError("release did not raise RELAYS first")
    if release_stage5 is None or release_stage5[1]["RC5"] != 1 or release_stage5[1]["RC6"] != 1 or release_stage5[1]["RC7"] != 0:
        raise AssertionError("release did not raise TX_VCC second")
    if release_done is None:
        raise AssertionError("release did not raise TX_BIAS last")


def validate_trip(samples, trip_name) -> None:
    expected_reason = f"FAULT: {trip_name}"
    trip = next((sample for sample in samples if block_reason(sample[2]) == expected_reason), None)
    if trip is None:
        raise AssertionError(f"{trip_name} trip was not reported")
    if trip[2]["g_ptt_active"] != "true":
        raise AssertionError(f"{trip_name} trip did not occur while PTT was active")
    if trip_name == "CURRENT" and not 3.85 <= trip[3]["RB1"] <= 4.10:
        raise AssertionError(f"current trip occurred at {trip[3]['RB1']:.3f}V, outside the expected 40A threshold")
    fault_samples = [sample for sample in samples
                     if (block_reason(sample[2]) or "").startswith("FAULT:")]
    if any(sample[2]["g_ptt_complete_display_active"] == "true" for sample in fault_samples):
        raise AssertionError(f"{trip_name} fault display was overwritten by PTT_COMPLETE")
    tx_active = next((sample for sample in samples
                      if sample[2]["g_sequence_stage"] == "3" and
                      (sample[1]["RC5"], sample[1]["RC6"], sample[1]["RC7"]) == (0, 0, 0)), None)
    if tx_active is None:
        raise AssertionError(f"{trip_name} trip did not follow an active TX state")
    active_ms = (trip[0] - tx_active[0]) * SECONDS_PER_INSTRUCTION * 1000
    if active_ms < 500:
        raise AssertionError(f"{trip_name} trip occurred after only {active_ms:.1f}ms of TX")
    print(f"TX active before {trip_name} trip: {active_ms:.1f}ms")
    shutdown = next((sample for sample in samples if sample[2]["g_trip_shutdown_active"] == "true"), None)
    if shutdown is None or (shutdown[1]["RC5"], shutdown[1]["RC6"], shutdown[1]["RC7"]) != (0, 1, 0):
        raise AssertionError("fault did not raise TX_VCC immediately before the delayed shutdown")
    shutdown_done = next((sample for sample in samples
                          if sample[2]["g_trip_shutdown_active"] == "false" and
                          block_reason(sample[2]) == expected_reason), None)
    if shutdown_done is None or (shutdown_done[1]["RC5"], shutdown_done[1]["RC6"], shutdown_done[1]["RC7"]) != (1, 1, 1):
        raise AssertionError("fault did not raise RELAYS and TX_BIAS after five milliseconds")
    if trip_name == "CURRENT" and any(sample[3]["RB1"] != 0.0
                                      for sample in samples[samples.index(trip) + 1:samples.index(shutdown_done) + 1]):
        raise AssertionError("current sensor did not fall to zero after the current trip")
    if trip_name == "TEMPERATURE":
        post_shutdown = samples[samples.index(shutdown_done):]
        if any((sample[1]["RC5"], sample[1]["RC6"], sample[1]["RC7"]) != (1, 1, 1)
               for sample in post_shutdown if sample[2]["g_fault_latched"] == "true"):
            raise AssertionError("temperature trip outputs did not remain high until recovery")
        recovered = next((sample for sample in samples[samples.index(shutdown_done) + 1:]
                          if sample[2]["g_fault_latched"] == "false" and
                          sample[2]["g_sequence_stage"] == "3"), None)
        if recovered is None or (recovered[1]["RC5"], recovered[1]["RC6"], recovered[1]["RC7"]) != (0, 0, 0):
            raise AssertionError("temperature recovery did not re-enter the active TX sequence")
        print("TEMP RECOVERED: TX sequence resumed after hysteresis")
    elif shutdown_done[2]["g_fault_latched"] != "true":
        raise AssertionError(f"{trip_name} fault unexpectedly recovered")
    else:
        recovered = next((sample for sample in samples[samples.index(shutdown_done) + 1:]
                          if sample[2]["g_fault_latched"] == "false" and
                          sample[2]["g_sequence_stage"] == "3"), None)
        if recovered is None:
            raise AssertionError(f"{trip_name} did not clear and re-enter TX after a PTT re-arm")
        if trip_name == "CURRENT" and recovered[3]["RB1"] > 2.95:
            raise AssertionError("current re-arm exceeded the 10A limit")
        print(f"{trip_name} cleared by PTT re-arm; TX sequence resumed")
    if trip_name == "TEMPERATURE" and trip[3]["RA5"] < 4.0:
        raise AssertionError("temperature ADC input did not rise above 4V")
    print(f"ADC voltages at {trip_name}: " +
          ", ".join(f"{pin}={trip[3][pin]:.3f}V" for pin in ADC_PINS))
    print(f"TRIP: {trip_name} ({expected_reason})")


def validate_swr1_1p5(samples) -> None:
    if any((block_reason(sample[2]) or "").startswith("FAULT:") for sample in samples):
        raise AssertionError("1.5:1 SWR incorrectly tripped")
    active = [sample for sample in samples
              if sample[2]["g_sequence_stage"] == "3" and
              (sample[1]["RC5"], sample[1]["RC6"], sample[1]["RC7"]) == (0, 0, 0)]
    if not active:
        raise AssertionError("1.5:1 SWR did not remain in active TX")
    active_ms = (samples[-1][0] - active[0][0]) * SECONDS_PER_INSTRUCTION * 1000
    if active_ms < 500:
        raise AssertionError(f"1.5:1 SWR was active for only {active_ms:.1f}ms")
    print(f"SWR1 1.50:1 at 2.000kW PEP: no trip; TX remained active for {active_ms:.1f}ms")


def parse_trace(output: str):
    """Walks the mdb transcript in order, tracking cumulative instruction count and
    each pin's/variable's most-recently-printed value, sampling a full snapshot every
    time all pins and state variables have been reprinted (i.e. once per Stepi block)."""
    samples = []
    instr_count = 0
    pending = {}
    pending_adc = {}
    pending_voltages = {}
    state_pending = {}
    awaiting_var = None
    for raw_line in output.splitlines():
        line = raw_line.strip()
        m_stepi = STEPI_RE.match(line)
        if m_stepi:
            instr_count += int(m_stepi.group(1))
            continue
        if awaiting_var is not None:
            if line:
                state_pending[awaiting_var] = line
                awaiting_var = None
            continue
        m_var = VAR_NAME_RE.match(line)
        if m_var:
            awaiting_var = m_var.group(1)
            continue
        m = PRINT_RE.match(line)
        if m:
            pin, level, volts = m.groups()
            pending[pin] = 1 if level == "HIGH" or (volts is not None and float(volts) >= 2.5) else 0
            if pin in ADC_PINS or pin == SCENARIO_MARKER_PIN:
                pending_adc[pin] = 1
                pending_voltages[pin] = float(volts) if volts is not None else (5.0 if level == "HIGH" else 0.0)
        if (len(pending) == len(PINS) + len(ADC_PINS) + 1 and
            len(pending_adc) == len(ADC_PINS) + 1 and len(state_pending) == len(STATE_VARS)):
            state_pending["_scenario_marker"] = pending_voltages[SCENARIO_MARKER_PIN]
            samples.append((instr_count, dict(pending), dict(state_pending), dict(pending_voltages)))
            pending.clear()
            pending_adc.clear()
            pending_voltages.clear()
            state_pending.clear()
    return samples


def write_trace_csv(samples, trace_name, csv_dir):
    csv_path = csv_dir / f"{trace_name}.csv"
    with open(csv_path, "w") as f:
        f.write("time_s," + ",".join(PIN_LABELS[p] for p in PINS) +
                "," + ",".join(f"ADC_{pin}_V" for pin in ADC_PINS) +
                ",g_ptt_active,g_sequence_stage,g_state,block_reason\n")
        for instr_count, vals, state, adc_voltages in samples:
            t = instr_count * SECONDS_PER_INSTRUCTION
            reason = block_reason(state) or ""
            f.write(f"{t:.6f}," + ",".join(str(vals[p]) for p in PINS) +
                    "," + ",".join(f"{adc_voltages[pin]:.3f}" for pin in ADC_PINS) +
                    f",{state['g_ptt_active']},{state['g_sequence_stage']},{state['g_state']},{reason}\n")
    return csv_path


def write_trace_graph(samples, trip_name, trace_name, graph_dir):
    try:
        import matplotlib.pyplot as plt
    except ImportError:
        return None
    times = [sample[0] * SECONDS_PER_INSTRUCTION * 1000 for sample in samples]
    graph_adc_pins = TRIP_ADC_PINS.get(trip_name, []) if trip_name else []
    graph_rows = [("digital", pin) for pin in PINS] + [("adc", pin) for pin in graph_adc_pins]
    fig, axes = plt.subplots(len(graph_rows), 1, sharex=True,
                             figsize=(10, max(6, len(graph_rows) * 1.25)))
    axes = list(axes) if hasattr(axes, "__len__") else [axes]
    trip_index = next((index for index, sample in enumerate(samples)
                       if trip_name in TRIP_NAMES and block_reason(sample[2]) == f"FAULT: {trip_name}"), None)
    trip_time = times[trip_index] if trip_index is not None else None
    complete_index = next((index for index, sample in enumerate(samples)
                           if sample[2]["g_ptt_complete_display_active"] == "true" and
                           (sample[1]["RC5"], sample[1]["RC6"], sample[1]["RC7"]) == (0, 0, 0)), None)
    lifecycle = [(times[0], "LCD: STARTUP")]
    ptt_index = next((index for index, sample in enumerate(samples) if sample[2]["g_ptt_active"] == "true"), None)
    if ptt_index is not None:
        lifecycle.append((times[ptt_index], "LCD: PTT REQ"))
    if complete_index is not None:
        lifecycle.append((times[complete_index], "LCD: PTT_COMPLETE"))
        restored_index = next((index for index, sample in enumerate(samples)
                               if index > complete_index and
                               sample[2]["g_transient_menu_display"] == "false"), None)
        if restored_index is not None:
            lifecycle.append((times[restored_index], "LCD: RESTORED USER PAGE"))
    if trip_time is not None:
        lifecycle.append((trip_time, f"LCD: TRIP {trip_name}"))
    for ax, (kind, pin) in zip(axes, graph_rows):
        if kind == "digital":
            ax.step(times, [sample[1][pin] for sample in samples], where="post")
            ax.set_ylim(-0.2, 1.2)
            ax.set_yticks([0, 1])
            label = PIN_LABELS[pin]
        else:
            values = [sample[3][pin] for sample in samples]
            ax.plot(times, values, drawstyle="steps-post")
            ax.set_ylim(-0.2, 5.2)
            label = f"ADC {ADC_LABELS[pin]}"
            if trip_index is not None:
                ax.annotate(f"{values[trip_index]:.3f} V", (times[trip_index], values[trip_index]),
                            xytext=(8, 4), textcoords="offset points", fontsize=8)
        ax.set_ylabel(f"{pin}\n{label}", rotation=0, labelpad=42, va="center")
        ax.grid(True, alpha=0.3)
    reasons = [block_reason(sample[2]) for sample in samples]
    span_start = 0
    span_reason = reasons[0]
    spans = []
    for index, reason in enumerate(reasons[1:], 1):
        if reason != span_reason:
            if span_reason:
                spans.append((times[span_start], times[index], span_reason))
            span_start, span_reason = index, reason
    if span_reason:
        spans.append((times[span_start], times[-1], span_reason))
    for start, end, reason in spans:
        for ax in axes:
            ax.axvspan(start, end, color="red", alpha=0.12)
        axes[0].text((start + end) / 2, 1.28, reason, ha="center", fontsize=7, color="red")
    for index, (marker_time, marker_label) in enumerate(lifecycle):
        axes[0].axvline(marker_time, color="steelblue", linestyle="-.", alpha=0.45)
        axes[0].text(marker_time, 1.42 + (index % 3) * 0.28, marker_label,
                 ha="center", fontsize=7, color="steelblue", clip_on=False)
    if trip_time is not None:
        axes[0].axvline(trip_time, color="red", linestyle="--", alpha=0.6)
    axes[0].set_xlim(0, times[-1])
    axes[-1].set_xlabel("time (ms, approx)")
    title = f"PTT sequencing with {trip_name} trip (simulated)" if trip_name else "PTT assert/release sequencing (simulated)"
    fig.suptitle(title)
    fig.tight_layout()
    graph_path = graph_dir / f"{trace_name}.png"
    fig.savefig(graph_path, dpi=120)
    plt.close(fig)
    return graph_path


def main():
    test_mode = "--test" in sys.argv[1:]
    trip_name = "TEMPERATURE" if "--temperature-trip" in sys.argv[1:] else None
    if "--swr1-1p5" in sys.argv[1:]:
        trip_name = "SWR1_1P5"
    if "--trip" in sys.argv[1:]:
        trip_name = sys.argv[sys.argv.index("--trip") + 1].upper()
    if trip_name is not None and trip_name not in TRIP_NAMES | NON_TRIP_NAMES:
        sys.exit(f"error: unknown trip {trip_name}")
    temperature_trip = trip_name == "TEMPERATURE"
    if "--suite" in sys.argv[1:]:
        scenario_names = [None, "TEMPERATURE", "SWR1", "SWR2", "HWFAULT",
                          "CURRENT", "OVERDRIVE", "DRAIN", "SWR1_1P5"]
        first_script = build_script(marker=0.0)
        suite_lines = first_script.splitlines()[:-1]
        for index, scenario in enumerate(scenario_names[1:], 1):
            scenario_lines = build_script(trip_name=scenario, marker=index * 0.5).splitlines()
            suite_lines.append("reset")
            suite_lines.extend(scenario_lines[3:-1])
        raw_output = run_mdb(mdb_path=find_mdb(), script="\n".join(suite_lines + ["quit"]))
        groups = [(index, parse_trace(chunk)) for index, chunk in enumerate(raw_output.split("Resetting SFRs"))]
        groups = [(marker, scenario_samples) for marker, scenario_samples in groups if scenario_samples]
        if len(groups) != len(scenario_names):
            raise AssertionError(f"suite produced {len(groups)} scenarios, expected {len(scenario_names)}")
        validate_sequence(groups[0][1])
        for scenario, (_, scenario_samples) in zip(scenario_names[1:], groups[1:]):
            if scenario == "SWR1_1P5":
                validate_swr1_1p5(scenario_samples)
            else:
                validate_trip(scenario_samples, scenario)
        out_dir = REPO_ROOT / "_build" / "My_Pic_Project" / "sim"
        csv_dir = out_dir / "csv"
        graph_dir = out_dir / "graphs"
        csv_dir.mkdir(parents=True, exist_ok=True)
        graph_dir.mkdir(parents=True, exist_ok=True)
        for scenario, (_, scenario_samples) in zip(scenario_names, groups):
            trace_name = f"{scenario.lower()}_trace" if scenario else "ptt_trace"
            write_trace_csv(scenario_samples, trace_name, csv_dir)
            write_trace_graph(scenario_samples, scenario, trace_name, graph_dir)
        print(f"PTT suite passed: {len(scenario_names)} scenarios in one MDB session")
        return
    if not ELF_PATH.exists():
        sys.exit(f"error: {ELF_PATH} not found - build firmware first (build_firmware.ps1/.sh)")
    mdb_path = find_mdb()
    script = build_script(trip_name=trip_name)
    output = run_mdb(mdb_path, script)
    samples = parse_trace(output)
    if not samples:
        sys.exit("error: no samples parsed from mdb output - dumping raw output:\n" + output[-4000:])
    if test_mode:
        validate_sequence(samples)
        print("PTT sequencing test passed")
    if trip_name:
        if trip_name in TRIP_NAMES:
            validate_trip(samples, trip_name)
        else:
            validate_swr1_1p5(samples)

    out_dir = REPO_ROOT / "_build" / "My_Pic_Project" / "sim"
    csv_dir = out_dir / "csv"
    graph_dir = out_dir / "graphs"
    csv_dir.mkdir(parents=True, exist_ok=True)
    graph_dir.mkdir(parents=True, exist_ok=True)
    trace_name = f"{trip_name.lower()}_trip_trace" if trip_name else "ptt_trace"
    csv_path = csv_dir / f"{trace_name}.csv"
    with open(csv_path, "w") as f:
        f.write("time_s," + ",".join(PIN_LABELS[p] for p in PINS) +
            "," + ",".join(f"ADC_{pin}_V" for pin in ADC_PINS) +
            ",g_ptt_active,g_sequence_stage,g_state,block_reason\n")
        for instr_count, vals, state, adc_voltages in samples:
            t = instr_count * SECONDS_PER_INSTRUCTION
            reason = block_reason(state) or ""
            f.write(f"{t:.6f}," + ",".join(str(vals[p]) for p in PINS) +
                "," + ",".join(f"{adc_voltages[pin]:.3f}" for pin in ADC_PINS) +
                f",{state['g_ptt_active']},{state['g_sequence_stage']},{state['g_state']},{reason}\n")
    print(f"Wrote {csv_path} ({len(samples)} samples)")

    # Print console FAULT/blocking-reason transitions so "why can't PTT key up" is obvious
    # without having to read the plot.
    last_reason = object()
    for instr_count, _vals, state, _adc_voltages in samples:
        reason = block_reason(state)
        if reason != last_reason:
            t = instr_count * SECONDS_PER_INSTRUCTION * 1000
            print(f"t={t:8.2f}ms  {reason if reason else 'PTT OK (no block)'}")
            last_reason = reason

    try:
        import matplotlib.pyplot as plt
    except ImportError:
        print("matplotlib not installed; skipping PNG (pip install matplotlib)")
        return

    times = [s[0] * SECONDS_PER_INSTRUCTION * 1000 for s in samples]  # ms
    reasons = [block_reason(s[2]) for s in samples]

    # Contiguous [start, end, reason] spans where PTT/TX is blocked, for shading/labeling.
    block_spans = []
    span_start = None
    span_reason = None
    for t, reason in zip(times, reasons):
        if reason != span_reason:
            if span_reason is not None:
                block_spans.append((span_start, t, span_reason))
            span_start, span_reason = t, reason
    if span_reason is not None:
        block_spans.append((span_start, times[-1], span_reason))

    graph_adc_pins = TRIP_ADC_PINS.get(trip_name, []) if trip_name else []
    graph_rows = [("digital", pin) for pin in PINS] + [("adc", pin) for pin in graph_adc_pins]
    fig, axes = plt.subplots(len(graph_rows), 1, sharex=True,
                             figsize=(10, max(6, len(graph_rows) * 1.25)))
    axes = list(axes) if hasattr(axes, "__len__") else [axes]
    trip_time = None
    shutdown_complete_time = None
    trip_index = None
    if trip_name in TRIP_NAMES:
        trip_index = next(index for index, sample in enumerate(samples)
                          if block_reason(sample[2]) == f"FAULT: {trip_name}")
        trip_time = times[trip_index]
        shutdown_complete_time = times[next(index for index, sample in enumerate(samples)
                                            if sample[2]["g_trip_shutdown_active"] == "false" and
                                            block_reason(sample[2]) == f"FAULT: {trip_name}")]
    lifecycle = [(times[0], "LCD: STARTUP")]
    ptt_index = next((index for index, sample in enumerate(samples)
                      if sample[2]["g_ptt_active"] == "true"), None)
    if ptt_index is not None:
        lifecycle.append((times[ptt_index], "LCD: PTT REQ"))
    complete_index = next((index for index, sample in enumerate(samples)
                           if sample[2]["g_ptt_complete_display_active"] == "true" and
                           (sample[1]["RC5"], sample[1]["RC6"], sample[1]["RC7"]) == (0, 0, 0)), None)
    if complete_index is not None:
        lifecycle.append((times[complete_index], "LCD: PTT_COMPLETE"))
    if trip_time is not None:
        lifecycle.append((trip_time, f"LCD: TRIP {trip_name}"))
    restored_index = next((index for index, sample in enumerate(samples)
                           if complete_index is not None and index > complete_index and
                           sample[2]["g_transient_menu_display"] == "false"), None)
    if restored_index is not None:
        lifecycle.append((times[restored_index], "LCD: RESTORED USER PAGE"))
    for ax, (kind, pin) in zip(axes, graph_rows):
        if kind == "digital":
            values = [s[1][pin] for s in samples]
            ax.step(times, values, where="post")
            ax.set_ylim(-0.2, 1.2)
            ax.set_yticks([0, 1])
            label = PIN_LABELS[pin]
        else:
            values = [s[3][pin] for s in samples]
            ax.plot(times, values, drawstyle="steps-post")
            ax.set_ylim(-0.2, 5.2)
            label = f"ADC {ADC_LABELS[pin]}"
            if trip_index is not None:
                ax.annotate(f"{values[trip_index]:.3f} V", (trip_time, values[trip_index]),
                            xytext=(8, 4), textcoords="offset points", fontsize=8)
        ax.set_ylabel(f"{pin}\n{label}", rotation=0, labelpad=42, va="center")
        ax.grid(True, alpha=0.3)
        for start, end, reason in block_spans:
            ax.axvspan(start, end, color="red", alpha=0.12)
        if trip_name in TRIP_NAMES:
            ax.axvline(trip_time, color="red", linestyle="--", alpha=0.6)
            ax.axvline(shutdown_complete_time, color="orange", linestyle=":", alpha=0.7)
    for start, end, reason in block_spans:
        axes[0].text((start + end) / 2, 1.28, reason, ha="center", va="bottom",
                     fontsize=7, color="red", clip_on=False)
    if trip_name in TRIP_NAMES:
        axes[2].annotate("2. RELAYS HIGH (+5 ms)",
                         xy=(shutdown_complete_time, 1), xytext=(8, 12),
                         textcoords="offset points", color="red", fontsize=8,
                         arrowprops={"arrowstyle": "->", "color": "red"})
        axes[3].annotate("1. TX_VCC HIGH (immediate)",
                         xy=(trip_time, 1), xytext=(8, 12),
                         textcoords="offset points", color="red", fontsize=8,
                         arrowprops={"arrowstyle": "->", "color": "red"})
        axes[4].annotate("3. TX_BIAS HIGH (+5 ms)",
                         xy=(shutdown_complete_time, 1), xytext=(8, 12),
                         textcoords="offset points", color="red", fontsize=8,
                         arrowprops={"arrowstyle": "->", "color": "red"})
    for marker_index, (marker_time, marker_label) in enumerate(lifecycle):
        axes[0].axvline(marker_time, color="steelblue", linestyle="-.", alpha=0.45)
        axes[0].text(marker_time, 1.42 + (marker_index % 3) * 0.28, marker_label,
                 ha="center", va="bottom", fontsize=7, color="steelblue",
                     clip_on=False)
    axes[0].set_xlim(0, times[-1])
    axes[-1].set_xlabel("time (ms, approx)")
    title = ("PTT sequencing with SWR1 1.5:1 no-trip (simulated)" if trip_name == "SWR1_1P5"
             else f"PTT sequencing with {trip_name} trip (simulated)" if trip_name
             else "PTT assert/release sequencing (simulated)")
    fig.suptitle(title)
    fig.tight_layout()
    png_path = graph_dir / f"{trace_name}.png"
    fig.savefig(png_path, dpi=120)
    print(f"Wrote {png_path}")
if __name__ == "__main__":
    main()

